// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AiDealBriefEp } from '../src/api/aiDealBrief';
import type { default as _AiDraftEmailEp } from '../src/api/aiDraftEmail';
import type { default as _AiNextStepsEp } from '../src/api/aiNextSteps';
import type { default as _BootstrapEp } from '../src/api/bootstrap';
import type { default as _ClearDemoDataEp } from '../src/api/clearDemoData';
import type { default as _ConvertLeadEp } from '../src/api/convertLead';
import type { default as _CreateCompanyEp } from '../src/api/createCompany';
import type { default as _CreateContactEp } from '../src/api/createContact';
import type { default as _CreateDealEp } from '../src/api/createDeal';
import type { default as _CreateLeadEp } from '../src/api/createLead';
import type { default as _CreateTaskEp } from '../src/api/createTask';
import type { default as _DeactivateMemberEp } from '../src/api/deactivateMember';
import type { default as _DeleteActivityEp } from '../src/api/deleteActivity';
import type { default as _DeleteAutomationEp } from '../src/api/deleteAutomation';
import type { default as _DeleteBookingPageEp } from '../src/api/deleteBookingPage';
import type { default as _DeleteChoiceEp } from '../src/api/deleteChoice';
import type { default as _DeleteCompaniesEp } from '../src/api/deleteCompanies';
import type { default as _DeleteContactsEp } from '../src/api/deleteContacts';
import type { default as _DeleteCustomFieldEp } from '../src/api/deleteCustomField';
import type { default as _DeleteDealsEp } from '../src/api/deleteDeals';
import type { default as _DeleteDocumentEp } from '../src/api/deleteDocument';
import type { default as _DeleteFormEp } from '../src/api/deleteForm';
import type { default as _DeleteLeadsEp } from '../src/api/deleteLeads';
import type { default as _DeleteProductEp } from '../src/api/deleteProduct';
import type { default as _DeleteSequenceEp } from '../src/api/deleteSequence';
import type { default as _DeleteStageEp } from '../src/api/deleteStage';
import type { default as _DeleteTagEp } from '../src/api/deleteTag';
import type { default as _DeleteTasksEp } from '../src/api/deleteTasks';
import type { default as _DeleteTeamEp } from '../src/api/deleteTeam';
import type { default as _DeleteTemplateEp } from '../src/api/deleteTemplate';
import type { default as _DeleteViewEp } from '../src/api/deleteView';
import type { default as _DuplicateQuoteEp } from '../src/api/duplicateQuote';
import type { default as _EnrollInSequenceEp } from '../src/api/enrollInSequence';
import type { default as _ExportRecordsEp } from '../src/api/exportRecords';
import type { default as _FindDuplicatesEp } from '../src/api/findDuplicates';
import type { default as _GetBookingPageEp } from '../src/api/getBookingPage';
import type { default as _GetCompanyEp } from '../src/api/getCompany';
import type { default as _GetContactEp } from '../src/api/getContact';
import type { default as _GetDealEp } from '../src/api/getDeal';
import type { default as _GetFormEp } from '../src/api/getForm';
import type { default as _GetHomeEp } from '../src/api/getHome';
import type { default as _GetLeadEp } from '../src/api/getLead';
import type { default as _GetPipelineDetailEp } from '../src/api/getPipelineDetail';
import type { default as _GetQuoteEp } from '../src/api/getQuote';
import type { default as _GetSequenceEp } from '../src/api/getSequence';
import type { default as _GetTimelineEp } from '../src/api/getTimeline';
import type { default as _ImportRecordsEp } from '../src/api/importRecords';
import type { default as _ListActivitiesEp } from '../src/api/listActivities';
import type { default as _ListAutomationRunsEp } from '../src/api/listAutomationRuns';
import type { default as _ListAutomationsEp } from '../src/api/listAutomations';
import type { default as _ListBookingPagesEp } from '../src/api/listBookingPages';
import type { default as _ListBookingsEp } from '../src/api/listBookings';
import type { default as _ListCompaniesEp } from '../src/api/listCompanies';
import type { default as _ListContactsEp } from '../src/api/listContacts';
import type { default as _ListDealsEp } from '../src/api/listDeals';
import type { default as _ListDocumentsEp } from '../src/api/listDocuments';
import type { default as _ListEnrollmentsEp } from '../src/api/listEnrollments';
import type { default as _ListFormsEp } from '../src/api/listForms';
import type { default as _ListImportsEp } from '../src/api/listImports';
import type { default as _ListLeadsEp } from '../src/api/listLeads';
import type { default as _ListLineItemsEp } from '../src/api/listLineItems';
import type { default as _ListNotificationsEp } from '../src/api/listNotifications';
import type { default as _ListProductsEp } from '../src/api/listProducts';
import type { default as _ListQuotasEp } from '../src/api/listQuotas';
import type { default as _ListQuotesEp } from '../src/api/listQuotes';
import type { default as _ListSequencesEp } from '../src/api/listSequences';
import type { default as _ListSubmissionsEp } from '../src/api/listSubmissions';
import type { default as _ListTasksEp } from '../src/api/listTasks';
import type { default as _ListTemplatesEp } from '../src/api/listTemplates';
import type { default as _LogActivityEp } from '../src/api/logActivity';
import type { default as _MarkNotificationsEp } from '../src/api/markNotifications';
import type { default as _MergeRecordsEp } from '../src/api/mergeRecords';
import type { default as _QuotePdfEp } from '../src/api/quotePdf';
import type { default as _ReorderStagesEp } from '../src/api/reorderStages';
import type { default as _ReportActivityEp } from '../src/api/reportActivity';
import type { default as _ReportForecastEp } from '../src/api/reportForecast';
import type { default as _ReportLeadsEp } from '../src/api/reportLeads';
import type { default as _ReportPipelineEp } from '../src/api/reportPipeline';
import type { default as _ReportTeamEp } from '../src/api/reportTeam';
import type { default as _RunAutomationNowEp } from '../src/api/runAutomationNow';
import type { default as _RunSequencesEp } from '../src/api/runSequences';
import type { default as _SaveAutomationEp } from '../src/api/saveAutomation';
import type { default as _SaveBookingPageEp } from '../src/api/saveBookingPage';
import type { default as _SaveChoiceEp } from '../src/api/saveChoice';
import type { default as _SaveCustomFieldEp } from '../src/api/saveCustomField';
import type { default as _SaveDocumentEp } from '../src/api/saveDocument';
import type { default as _SaveFormEp } from '../src/api/saveForm';
import type { default as _SaveLineItemsEp } from '../src/api/saveLineItems';
import type { default as _SaveMemberEp } from '../src/api/saveMember';
import type { default as _SavePipelineEp } from '../src/api/savePipeline';
import type { default as _SaveProductEp } from '../src/api/saveProduct';
import type { default as _SaveQuotaEp } from '../src/api/saveQuota';
import type { default as _SaveQuoteEp } from '../src/api/saveQuote';
import type { default as _SaveSequenceEp } from '../src/api/saveSequence';
import type { default as _SaveStageEp } from '../src/api/saveStage';
import type { default as _SaveTagEp } from '../src/api/saveTag';
import type { default as _SaveTeamEp } from '../src/api/saveTeam';
import type { default as _SaveTemplateEp } from '../src/api/saveTemplate';
import type { default as _SaveViewEp } from '../src/api/saveView';
import type { default as _SearchEp } from '../src/api/search';
import type { default as _SeedWorkspaceEp } from '../src/api/seedWorkspace';
import type { default as _SendDigestEp } from '../src/api/sendDigest';
import type { default as _SendEmailEp } from '../src/api/sendEmail';
import type { default as _SendQuoteEp } from '../src/api/sendQuote';
import type { default as _SetDealContactsEp } from '../src/api/setDealContacts';
import type { default as _SweepStalledDealsEp } from '../src/api/sweepStalledDeals';
import type { default as _UndoImportEp } from '../src/api/undoImport';
import type { default as _UpdateActivityEp } from '../src/api/updateActivity';
import type { default as _UpdateCompaniesEp } from '../src/api/updateCompanies';
import type { default as _UpdateContactsEp } from '../src/api/updateContacts';
import type { default as _UpdateDealsEp } from '../src/api/updateDeals';
import type { default as _UpdateEnrollmentsEp } from '../src/api/updateEnrollments';
import type { default as _UpdateLeadsEp } from '../src/api/updateLeads';
import type { default as _UpdateOrgSettingsEp } from '../src/api/updateOrgSettings';
import type { default as _UpdateProfileEp } from '../src/api/updateProfile';
import type { default as _UpdateTasksEp } from '../src/api/updateTasks';
import type { default as _VoidQuoteEp } from '../src/api/voidQuote';

type _AiDealBriefCfg = typeof _AiDealBriefEp;
export type AiDealBriefInputType = NonNullable<_AiDealBriefCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiDealBriefCfg['execute']>[0]['input'];
export type AiDealBriefOutputType = Awaited<ReturnType<_AiDealBriefCfg['execute']>>;
export const aiDealBrief = createCaller<AiDealBriefInputType, AiDealBriefOutputType>('aiDealBrief');

type _AiDraftEmailCfg = typeof _AiDraftEmailEp;
export type AiDraftEmailInputType = NonNullable<_AiDraftEmailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiDraftEmailCfg['execute']>[0]['input'];
export type AiDraftEmailOutputType = Awaited<ReturnType<_AiDraftEmailCfg['execute']>>;
export const aiDraftEmail = createCaller<AiDraftEmailInputType, AiDraftEmailOutputType>('aiDraftEmail');

type _AiNextStepsCfg = typeof _AiNextStepsEp;
export type AiNextStepsInputType = NonNullable<_AiNextStepsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiNextStepsCfg['execute']>[0]['input'];
export type AiNextStepsOutputType = Awaited<ReturnType<_AiNextStepsCfg['execute']>>;
export const aiNextSteps = createCaller<AiNextStepsInputType, AiNextStepsOutputType>('aiNextSteps');

type _BootstrapCfg = typeof _BootstrapEp;
export type BootstrapInputType = NonNullable<_BootstrapCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BootstrapCfg['execute']>[0]['input'];
export type BootstrapOutputType = Awaited<ReturnType<_BootstrapCfg['execute']>>;
export const bootstrap = createCaller<BootstrapInputType, BootstrapOutputType>('bootstrap');

type _ClearDemoDataCfg = typeof _ClearDemoDataEp;
export type ClearDemoDataInputType = NonNullable<_ClearDemoDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ClearDemoDataCfg['execute']>[0]['input'];
export type ClearDemoDataOutputType = Awaited<ReturnType<_ClearDemoDataCfg['execute']>>;
export const clearDemoData = createCaller<ClearDemoDataInputType, ClearDemoDataOutputType>('clearDemoData');

type _ConvertLeadCfg = typeof _ConvertLeadEp;
export type ConvertLeadInputType = NonNullable<_ConvertLeadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ConvertLeadCfg['execute']>[0]['input'];
export type ConvertLeadOutputType = Awaited<ReturnType<_ConvertLeadCfg['execute']>>;
export const convertLead = createCaller<ConvertLeadInputType, ConvertLeadOutputType>('convertLead');

type _CreateCompanyCfg = typeof _CreateCompanyEp;
export type CreateCompanyInputType = NonNullable<_CreateCompanyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateCompanyCfg['execute']>[0]['input'];
export type CreateCompanyOutputType = Awaited<ReturnType<_CreateCompanyCfg['execute']>>;
export const createCompany = createCaller<CreateCompanyInputType, CreateCompanyOutputType>('createCompany');

type _CreateContactCfg = typeof _CreateContactEp;
export type CreateContactInputType = NonNullable<_CreateContactCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateContactCfg['execute']>[0]['input'];
export type CreateContactOutputType = Awaited<ReturnType<_CreateContactCfg['execute']>>;
export const createContact = createCaller<CreateContactInputType, CreateContactOutputType>('createContact');

type _CreateDealCfg = typeof _CreateDealEp;
export type CreateDealInputType = NonNullable<_CreateDealCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateDealCfg['execute']>[0]['input'];
export type CreateDealOutputType = Awaited<ReturnType<_CreateDealCfg['execute']>>;
export const createDeal = createCaller<CreateDealInputType, CreateDealOutputType>('createDeal');

type _CreateLeadCfg = typeof _CreateLeadEp;
export type CreateLeadInputType = NonNullable<_CreateLeadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateLeadCfg['execute']>[0]['input'];
export type CreateLeadOutputType = Awaited<ReturnType<_CreateLeadCfg['execute']>>;
export const createLead = createCaller<CreateLeadInputType, CreateLeadOutputType>('createLead');

type _CreateTaskCfg = typeof _CreateTaskEp;
export type CreateTaskInputType = NonNullable<_CreateTaskCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateTaskCfg['execute']>[0]['input'];
export type CreateTaskOutputType = Awaited<ReturnType<_CreateTaskCfg['execute']>>;
export const createTask = createCaller<CreateTaskInputType, CreateTaskOutputType>('createTask');

type _DeactivateMemberCfg = typeof _DeactivateMemberEp;
export type DeactivateMemberInputType = NonNullable<_DeactivateMemberCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeactivateMemberCfg['execute']>[0]['input'];
export type DeactivateMemberOutputType = Awaited<ReturnType<_DeactivateMemberCfg['execute']>>;
export const deactivateMember = createCaller<DeactivateMemberInputType, DeactivateMemberOutputType>('deactivateMember');

type _DeleteActivityCfg = typeof _DeleteActivityEp;
export type DeleteActivityInputType = NonNullable<_DeleteActivityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteActivityCfg['execute']>[0]['input'];
export type DeleteActivityOutputType = Awaited<ReturnType<_DeleteActivityCfg['execute']>>;
export const deleteActivity = createCaller<DeleteActivityInputType, DeleteActivityOutputType>('deleteActivity');

type _DeleteAutomationCfg = typeof _DeleteAutomationEp;
export type DeleteAutomationInputType = NonNullable<_DeleteAutomationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteAutomationCfg['execute']>[0]['input'];
export type DeleteAutomationOutputType = Awaited<ReturnType<_DeleteAutomationCfg['execute']>>;
export const deleteAutomation = createCaller<DeleteAutomationInputType, DeleteAutomationOutputType>('deleteAutomation');

type _DeleteBookingPageCfg = typeof _DeleteBookingPageEp;
export type DeleteBookingPageInputType = NonNullable<_DeleteBookingPageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteBookingPageCfg['execute']>[0]['input'];
export type DeleteBookingPageOutputType = Awaited<ReturnType<_DeleteBookingPageCfg['execute']>>;
export const deleteBookingPage = createCaller<DeleteBookingPageInputType, DeleteBookingPageOutputType>('deleteBookingPage');

type _DeleteChoiceCfg = typeof _DeleteChoiceEp;
export type DeleteChoiceInputType = NonNullable<_DeleteChoiceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteChoiceCfg['execute']>[0]['input'];
export type DeleteChoiceOutputType = Awaited<ReturnType<_DeleteChoiceCfg['execute']>>;
export const deleteChoice = createCaller<DeleteChoiceInputType, DeleteChoiceOutputType>('deleteChoice');

type _DeleteCompaniesCfg = typeof _DeleteCompaniesEp;
export type DeleteCompaniesInputType = NonNullable<_DeleteCompaniesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteCompaniesCfg['execute']>[0]['input'];
export type DeleteCompaniesOutputType = Awaited<ReturnType<_DeleteCompaniesCfg['execute']>>;
export const deleteCompanies = createCaller<DeleteCompaniesInputType, DeleteCompaniesOutputType>('deleteCompanies');

type _DeleteContactsCfg = typeof _DeleteContactsEp;
export type DeleteContactsInputType = NonNullable<_DeleteContactsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteContactsCfg['execute']>[0]['input'];
export type DeleteContactsOutputType = Awaited<ReturnType<_DeleteContactsCfg['execute']>>;
export const deleteContacts = createCaller<DeleteContactsInputType, DeleteContactsOutputType>('deleteContacts');

type _DeleteCustomFieldCfg = typeof _DeleteCustomFieldEp;
export type DeleteCustomFieldInputType = NonNullable<_DeleteCustomFieldCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteCustomFieldCfg['execute']>[0]['input'];
export type DeleteCustomFieldOutputType = Awaited<ReturnType<_DeleteCustomFieldCfg['execute']>>;
export const deleteCustomField = createCaller<DeleteCustomFieldInputType, DeleteCustomFieldOutputType>('deleteCustomField');

type _DeleteDealsCfg = typeof _DeleteDealsEp;
export type DeleteDealsInputType = NonNullable<_DeleteDealsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteDealsCfg['execute']>[0]['input'];
export type DeleteDealsOutputType = Awaited<ReturnType<_DeleteDealsCfg['execute']>>;
export const deleteDeals = createCaller<DeleteDealsInputType, DeleteDealsOutputType>('deleteDeals');

type _DeleteDocumentCfg = typeof _DeleteDocumentEp;
export type DeleteDocumentInputType = NonNullable<_DeleteDocumentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteDocumentCfg['execute']>[0]['input'];
export type DeleteDocumentOutputType = Awaited<ReturnType<_DeleteDocumentCfg['execute']>>;
export const deleteDocument = createCaller<DeleteDocumentInputType, DeleteDocumentOutputType>('deleteDocument');

type _DeleteFormCfg = typeof _DeleteFormEp;
export type DeleteFormInputType = NonNullable<_DeleteFormCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteFormCfg['execute']>[0]['input'];
export type DeleteFormOutputType = Awaited<ReturnType<_DeleteFormCfg['execute']>>;
export const deleteForm = createCaller<DeleteFormInputType, DeleteFormOutputType>('deleteForm');

type _DeleteLeadsCfg = typeof _DeleteLeadsEp;
export type DeleteLeadsInputType = NonNullable<_DeleteLeadsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteLeadsCfg['execute']>[0]['input'];
export type DeleteLeadsOutputType = Awaited<ReturnType<_DeleteLeadsCfg['execute']>>;
export const deleteLeads = createCaller<DeleteLeadsInputType, DeleteLeadsOutputType>('deleteLeads');

type _DeleteProductCfg = typeof _DeleteProductEp;
export type DeleteProductInputType = NonNullable<_DeleteProductCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteProductCfg['execute']>[0]['input'];
export type DeleteProductOutputType = Awaited<ReturnType<_DeleteProductCfg['execute']>>;
export const deleteProduct = createCaller<DeleteProductInputType, DeleteProductOutputType>('deleteProduct');

type _DeleteSequenceCfg = typeof _DeleteSequenceEp;
export type DeleteSequenceInputType = NonNullable<_DeleteSequenceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteSequenceCfg['execute']>[0]['input'];
export type DeleteSequenceOutputType = Awaited<ReturnType<_DeleteSequenceCfg['execute']>>;
export const deleteSequence = createCaller<DeleteSequenceInputType, DeleteSequenceOutputType>('deleteSequence');

type _DeleteStageCfg = typeof _DeleteStageEp;
export type DeleteStageInputType = NonNullable<_DeleteStageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteStageCfg['execute']>[0]['input'];
export type DeleteStageOutputType = Awaited<ReturnType<_DeleteStageCfg['execute']>>;
export const deleteStage = createCaller<DeleteStageInputType, DeleteStageOutputType>('deleteStage');

type _DeleteTagCfg = typeof _DeleteTagEp;
export type DeleteTagInputType = NonNullable<_DeleteTagCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteTagCfg['execute']>[0]['input'];
export type DeleteTagOutputType = Awaited<ReturnType<_DeleteTagCfg['execute']>>;
export const deleteTag = createCaller<DeleteTagInputType, DeleteTagOutputType>('deleteTag');

type _DeleteTasksCfg = typeof _DeleteTasksEp;
export type DeleteTasksInputType = NonNullable<_DeleteTasksCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteTasksCfg['execute']>[0]['input'];
export type DeleteTasksOutputType = Awaited<ReturnType<_DeleteTasksCfg['execute']>>;
export const deleteTasks = createCaller<DeleteTasksInputType, DeleteTasksOutputType>('deleteTasks');

type _DeleteTeamCfg = typeof _DeleteTeamEp;
export type DeleteTeamInputType = NonNullable<_DeleteTeamCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteTeamCfg['execute']>[0]['input'];
export type DeleteTeamOutputType = Awaited<ReturnType<_DeleteTeamCfg['execute']>>;
export const deleteTeam = createCaller<DeleteTeamInputType, DeleteTeamOutputType>('deleteTeam');

type _DeleteTemplateCfg = typeof _DeleteTemplateEp;
export type DeleteTemplateInputType = NonNullable<_DeleteTemplateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteTemplateCfg['execute']>[0]['input'];
export type DeleteTemplateOutputType = Awaited<ReturnType<_DeleteTemplateCfg['execute']>>;
export const deleteTemplate = createCaller<DeleteTemplateInputType, DeleteTemplateOutputType>('deleteTemplate');

type _DeleteViewCfg = typeof _DeleteViewEp;
export type DeleteViewInputType = NonNullable<_DeleteViewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteViewCfg['execute']>[0]['input'];
export type DeleteViewOutputType = Awaited<ReturnType<_DeleteViewCfg['execute']>>;
export const deleteView = createCaller<DeleteViewInputType, DeleteViewOutputType>('deleteView');

type _DuplicateQuoteCfg = typeof _DuplicateQuoteEp;
export type DuplicateQuoteInputType = NonNullable<_DuplicateQuoteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DuplicateQuoteCfg['execute']>[0]['input'];
export type DuplicateQuoteOutputType = Awaited<ReturnType<_DuplicateQuoteCfg['execute']>>;
export const duplicateQuote = createCaller<DuplicateQuoteInputType, DuplicateQuoteOutputType>('duplicateQuote');

type _EnrollInSequenceCfg = typeof _EnrollInSequenceEp;
export type EnrollInSequenceInputType = NonNullable<_EnrollInSequenceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_EnrollInSequenceCfg['execute']>[0]['input'];
export type EnrollInSequenceOutputType = Awaited<ReturnType<_EnrollInSequenceCfg['execute']>>;
export const enrollInSequence = createCaller<EnrollInSequenceInputType, EnrollInSequenceOutputType>('enrollInSequence');

type _ExportRecordsCfg = typeof _ExportRecordsEp;
export type ExportRecordsInputType = NonNullable<_ExportRecordsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ExportRecordsCfg['execute']>[0]['input'];
export type ExportRecordsOutputType = Awaited<ReturnType<_ExportRecordsCfg['execute']>>;
export const exportRecords = createCaller<ExportRecordsInputType, ExportRecordsOutputType>('exportRecords');

type _FindDuplicatesCfg = typeof _FindDuplicatesEp;
export type FindDuplicatesInputType = NonNullable<_FindDuplicatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_FindDuplicatesCfg['execute']>[0]['input'];
export type FindDuplicatesOutputType = Awaited<ReturnType<_FindDuplicatesCfg['execute']>>;
export const findDuplicates = createCaller<FindDuplicatesInputType, FindDuplicatesOutputType>('findDuplicates');

type _GetBookingPageCfg = typeof _GetBookingPageEp;
export type GetBookingPageInputType = NonNullable<_GetBookingPageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBookingPageCfg['execute']>[0]['input'];
export type GetBookingPageOutputType = Awaited<ReturnType<_GetBookingPageCfg['execute']>>;
export const getBookingPage = createCaller<GetBookingPageInputType, GetBookingPageOutputType>('getBookingPage');

type _GetCompanyCfg = typeof _GetCompanyEp;
export type GetCompanyInputType = NonNullable<_GetCompanyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCompanyCfg['execute']>[0]['input'];
export type GetCompanyOutputType = Awaited<ReturnType<_GetCompanyCfg['execute']>>;
export const getCompany = createCaller<GetCompanyInputType, GetCompanyOutputType>('getCompany');

type _GetContactCfg = typeof _GetContactEp;
export type GetContactInputType = NonNullable<_GetContactCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetContactCfg['execute']>[0]['input'];
export type GetContactOutputType = Awaited<ReturnType<_GetContactCfg['execute']>>;
export const getContact = createCaller<GetContactInputType, GetContactOutputType>('getContact');

type _GetDealCfg = typeof _GetDealEp;
export type GetDealInputType = NonNullable<_GetDealCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetDealCfg['execute']>[0]['input'];
export type GetDealOutputType = Awaited<ReturnType<_GetDealCfg['execute']>>;
export const getDeal = createCaller<GetDealInputType, GetDealOutputType>('getDeal');

type _GetFormCfg = typeof _GetFormEp;
export type GetFormInputType = NonNullable<_GetFormCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetFormCfg['execute']>[0]['input'];
export type GetFormOutputType = Awaited<ReturnType<_GetFormCfg['execute']>>;
export const getForm = createCaller<GetFormInputType, GetFormOutputType>('getForm');

type _GetHomeCfg = typeof _GetHomeEp;
export type GetHomeInputType = NonNullable<_GetHomeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetHomeCfg['execute']>[0]['input'];
export type GetHomeOutputType = Awaited<ReturnType<_GetHomeCfg['execute']>>;
export const getHome = createCaller<GetHomeInputType, GetHomeOutputType>('getHome');

type _GetLeadCfg = typeof _GetLeadEp;
export type GetLeadInputType = NonNullable<_GetLeadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetLeadCfg['execute']>[0]['input'];
export type GetLeadOutputType = Awaited<ReturnType<_GetLeadCfg['execute']>>;
export const getLead = createCaller<GetLeadInputType, GetLeadOutputType>('getLead');

type _GetPipelineDetailCfg = typeof _GetPipelineDetailEp;
export type GetPipelineDetailInputType = NonNullable<_GetPipelineDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPipelineDetailCfg['execute']>[0]['input'];
export type GetPipelineDetailOutputType = Awaited<ReturnType<_GetPipelineDetailCfg['execute']>>;
export const getPipelineDetail = createCaller<GetPipelineDetailInputType, GetPipelineDetailOutputType>('getPipelineDetail');

type _GetQuoteCfg = typeof _GetQuoteEp;
export type GetQuoteInputType = NonNullable<_GetQuoteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetQuoteCfg['execute']>[0]['input'];
export type GetQuoteOutputType = Awaited<ReturnType<_GetQuoteCfg['execute']>>;
export const getQuote = createCaller<GetQuoteInputType, GetQuoteOutputType>('getQuote');

type _GetSequenceCfg = typeof _GetSequenceEp;
export type GetSequenceInputType = NonNullable<_GetSequenceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSequenceCfg['execute']>[0]['input'];
export type GetSequenceOutputType = Awaited<ReturnType<_GetSequenceCfg['execute']>>;
export const getSequence = createCaller<GetSequenceInputType, GetSequenceOutputType>('getSequence');

type _GetTimelineCfg = typeof _GetTimelineEp;
export type GetTimelineInputType = NonNullable<_GetTimelineCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetTimelineCfg['execute']>[0]['input'];
export type GetTimelineOutputType = Awaited<ReturnType<_GetTimelineCfg['execute']>>;
export const getTimeline = createCaller<GetTimelineInputType, GetTimelineOutputType>('getTimeline');

type _ImportRecordsCfg = typeof _ImportRecordsEp;
export type ImportRecordsInputType = NonNullable<_ImportRecordsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ImportRecordsCfg['execute']>[0]['input'];
export type ImportRecordsOutputType = Awaited<ReturnType<_ImportRecordsCfg['execute']>>;
export const importRecords = createCaller<ImportRecordsInputType, ImportRecordsOutputType>('importRecords');

type _ListActivitiesCfg = typeof _ListActivitiesEp;
export type ListActivitiesInputType = NonNullable<_ListActivitiesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListActivitiesCfg['execute']>[0]['input'];
export type ListActivitiesOutputType = Awaited<ReturnType<_ListActivitiesCfg['execute']>>;
export const listActivities = createCaller<ListActivitiesInputType, ListActivitiesOutputType>('listActivities');

type _ListAutomationRunsCfg = typeof _ListAutomationRunsEp;
export type ListAutomationRunsInputType = NonNullable<_ListAutomationRunsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListAutomationRunsCfg['execute']>[0]['input'];
export type ListAutomationRunsOutputType = Awaited<ReturnType<_ListAutomationRunsCfg['execute']>>;
export const listAutomationRuns = createCaller<ListAutomationRunsInputType, ListAutomationRunsOutputType>('listAutomationRuns');

type _ListAutomationsCfg = typeof _ListAutomationsEp;
export type ListAutomationsInputType = NonNullable<_ListAutomationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListAutomationsCfg['execute']>[0]['input'];
export type ListAutomationsOutputType = Awaited<ReturnType<_ListAutomationsCfg['execute']>>;
export const listAutomations = createCaller<ListAutomationsInputType, ListAutomationsOutputType>('listAutomations');

type _ListBookingPagesCfg = typeof _ListBookingPagesEp;
export type ListBookingPagesInputType = NonNullable<_ListBookingPagesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListBookingPagesCfg['execute']>[0]['input'];
export type ListBookingPagesOutputType = Awaited<ReturnType<_ListBookingPagesCfg['execute']>>;
export const listBookingPages = createCaller<ListBookingPagesInputType, ListBookingPagesOutputType>('listBookingPages');

type _ListBookingsCfg = typeof _ListBookingsEp;
export type ListBookingsInputType = NonNullable<_ListBookingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListBookingsCfg['execute']>[0]['input'];
export type ListBookingsOutputType = Awaited<ReturnType<_ListBookingsCfg['execute']>>;
export const listBookings = createCaller<ListBookingsInputType, ListBookingsOutputType>('listBookings');

type _ListCompaniesCfg = typeof _ListCompaniesEp;
export type ListCompaniesInputType = NonNullable<_ListCompaniesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListCompaniesCfg['execute']>[0]['input'];
export type ListCompaniesOutputType = Awaited<ReturnType<_ListCompaniesCfg['execute']>>;
export const listCompanies = createCaller<ListCompaniesInputType, ListCompaniesOutputType>('listCompanies');

type _ListContactsCfg = typeof _ListContactsEp;
export type ListContactsInputType = NonNullable<_ListContactsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListContactsCfg['execute']>[0]['input'];
export type ListContactsOutputType = Awaited<ReturnType<_ListContactsCfg['execute']>>;
export const listContacts = createCaller<ListContactsInputType, ListContactsOutputType>('listContacts');

type _ListDealsCfg = typeof _ListDealsEp;
export type ListDealsInputType = NonNullable<_ListDealsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListDealsCfg['execute']>[0]['input'];
export type ListDealsOutputType = Awaited<ReturnType<_ListDealsCfg['execute']>>;
export const listDeals = createCaller<ListDealsInputType, ListDealsOutputType>('listDeals');

type _ListDocumentsCfg = typeof _ListDocumentsEp;
export type ListDocumentsInputType = NonNullable<_ListDocumentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListDocumentsCfg['execute']>[0]['input'];
export type ListDocumentsOutputType = Awaited<ReturnType<_ListDocumentsCfg['execute']>>;
export const listDocuments = createCaller<ListDocumentsInputType, ListDocumentsOutputType>('listDocuments');

type _ListEnrollmentsCfg = typeof _ListEnrollmentsEp;
export type ListEnrollmentsInputType = NonNullable<_ListEnrollmentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListEnrollmentsCfg['execute']>[0]['input'];
export type ListEnrollmentsOutputType = Awaited<ReturnType<_ListEnrollmentsCfg['execute']>>;
export const listEnrollments = createCaller<ListEnrollmentsInputType, ListEnrollmentsOutputType>('listEnrollments');

type _ListFormsCfg = typeof _ListFormsEp;
export type ListFormsInputType = NonNullable<_ListFormsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListFormsCfg['execute']>[0]['input'];
export type ListFormsOutputType = Awaited<ReturnType<_ListFormsCfg['execute']>>;
export const listForms = createCaller<ListFormsInputType, ListFormsOutputType>('listForms');

type _ListImportsCfg = typeof _ListImportsEp;
export type ListImportsInputType = NonNullable<_ListImportsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListImportsCfg['execute']>[0]['input'];
export type ListImportsOutputType = Awaited<ReturnType<_ListImportsCfg['execute']>>;
export const listImports = createCaller<ListImportsInputType, ListImportsOutputType>('listImports');

type _ListLeadsCfg = typeof _ListLeadsEp;
export type ListLeadsInputType = NonNullable<_ListLeadsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListLeadsCfg['execute']>[0]['input'];
export type ListLeadsOutputType = Awaited<ReturnType<_ListLeadsCfg['execute']>>;
export const listLeads = createCaller<ListLeadsInputType, ListLeadsOutputType>('listLeads');

type _ListLineItemsCfg = typeof _ListLineItemsEp;
export type ListLineItemsInputType = NonNullable<_ListLineItemsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListLineItemsCfg['execute']>[0]['input'];
export type ListLineItemsOutputType = Awaited<ReturnType<_ListLineItemsCfg['execute']>>;
export const listLineItems = createCaller<ListLineItemsInputType, ListLineItemsOutputType>('listLineItems');

type _ListNotificationsCfg = typeof _ListNotificationsEp;
export type ListNotificationsInputType = NonNullable<_ListNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListNotificationsCfg['execute']>[0]['input'];
export type ListNotificationsOutputType = Awaited<ReturnType<_ListNotificationsCfg['execute']>>;
export const listNotifications = createCaller<ListNotificationsInputType, ListNotificationsOutputType>('listNotifications');

type _ListProductsCfg = typeof _ListProductsEp;
export type ListProductsInputType = NonNullable<_ListProductsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListProductsCfg['execute']>[0]['input'];
export type ListProductsOutputType = Awaited<ReturnType<_ListProductsCfg['execute']>>;
export const listProducts = createCaller<ListProductsInputType, ListProductsOutputType>('listProducts');

type _ListQuotasCfg = typeof _ListQuotasEp;
export type ListQuotasInputType = NonNullable<_ListQuotasCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListQuotasCfg['execute']>[0]['input'];
export type ListQuotasOutputType = Awaited<ReturnType<_ListQuotasCfg['execute']>>;
export const listQuotas = createCaller<ListQuotasInputType, ListQuotasOutputType>('listQuotas');

type _ListQuotesCfg = typeof _ListQuotesEp;
export type ListQuotesInputType = NonNullable<_ListQuotesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListQuotesCfg['execute']>[0]['input'];
export type ListQuotesOutputType = Awaited<ReturnType<_ListQuotesCfg['execute']>>;
export const listQuotes = createCaller<ListQuotesInputType, ListQuotesOutputType>('listQuotes');

type _ListSequencesCfg = typeof _ListSequencesEp;
export type ListSequencesInputType = NonNullable<_ListSequencesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListSequencesCfg['execute']>[0]['input'];
export type ListSequencesOutputType = Awaited<ReturnType<_ListSequencesCfg['execute']>>;
export const listSequences = createCaller<ListSequencesInputType, ListSequencesOutputType>('listSequences');

type _ListSubmissionsCfg = typeof _ListSubmissionsEp;
export type ListSubmissionsInputType = NonNullable<_ListSubmissionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListSubmissionsCfg['execute']>[0]['input'];
export type ListSubmissionsOutputType = Awaited<ReturnType<_ListSubmissionsCfg['execute']>>;
export const listSubmissions = createCaller<ListSubmissionsInputType, ListSubmissionsOutputType>('listSubmissions');

type _ListTasksCfg = typeof _ListTasksEp;
export type ListTasksInputType = NonNullable<_ListTasksCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListTasksCfg['execute']>[0]['input'];
export type ListTasksOutputType = Awaited<ReturnType<_ListTasksCfg['execute']>>;
export const listTasks = createCaller<ListTasksInputType, ListTasksOutputType>('listTasks');

type _ListTemplatesCfg = typeof _ListTemplatesEp;
export type ListTemplatesInputType = NonNullable<_ListTemplatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListTemplatesCfg['execute']>[0]['input'];
export type ListTemplatesOutputType = Awaited<ReturnType<_ListTemplatesCfg['execute']>>;
export const listTemplates = createCaller<ListTemplatesInputType, ListTemplatesOutputType>('listTemplates');

type _LogActivityCfg = typeof _LogActivityEp;
export type LogActivityInputType = NonNullable<_LogActivityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_LogActivityCfg['execute']>[0]['input'];
export type LogActivityOutputType = Awaited<ReturnType<_LogActivityCfg['execute']>>;
export const logActivity = createCaller<LogActivityInputType, LogActivityOutputType>('logActivity');

type _MarkNotificationsCfg = typeof _MarkNotificationsEp;
export type MarkNotificationsInputType = NonNullable<_MarkNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MarkNotificationsCfg['execute']>[0]['input'];
export type MarkNotificationsOutputType = Awaited<ReturnType<_MarkNotificationsCfg['execute']>>;
export const markNotifications = createCaller<MarkNotificationsInputType, MarkNotificationsOutputType>('markNotifications');

type _MergeRecordsCfg = typeof _MergeRecordsEp;
export type MergeRecordsInputType = NonNullable<_MergeRecordsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MergeRecordsCfg['execute']>[0]['input'];
export type MergeRecordsOutputType = Awaited<ReturnType<_MergeRecordsCfg['execute']>>;
export const mergeRecords = createCaller<MergeRecordsInputType, MergeRecordsOutputType>('mergeRecords');

type _QuotePdfCfg = typeof _QuotePdfEp;
export type QuotePdfInputType = NonNullable<_QuotePdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_QuotePdfCfg['execute']>[0]['input'];
export type QuotePdfOutputType = Awaited<ReturnType<_QuotePdfCfg['execute']>>;
export const quotePdf = createCaller<QuotePdfInputType, QuotePdfOutputType>('quotePdf');

type _ReorderStagesCfg = typeof _ReorderStagesEp;
export type ReorderStagesInputType = NonNullable<_ReorderStagesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReorderStagesCfg['execute']>[0]['input'];
export type ReorderStagesOutputType = Awaited<ReturnType<_ReorderStagesCfg['execute']>>;
export const reorderStages = createCaller<ReorderStagesInputType, ReorderStagesOutputType>('reorderStages');

type _ReportActivityCfg = typeof _ReportActivityEp;
export type ReportActivityInputType = NonNullable<_ReportActivityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportActivityCfg['execute']>[0]['input'];
export type ReportActivityOutputType = Awaited<ReturnType<_ReportActivityCfg['execute']>>;
export const reportActivity = createCaller<ReportActivityInputType, ReportActivityOutputType>('reportActivity');

type _ReportForecastCfg = typeof _ReportForecastEp;
export type ReportForecastInputType = NonNullable<_ReportForecastCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportForecastCfg['execute']>[0]['input'];
export type ReportForecastOutputType = Awaited<ReturnType<_ReportForecastCfg['execute']>>;
export const reportForecast = createCaller<ReportForecastInputType, ReportForecastOutputType>('reportForecast');

type _ReportLeadsCfg = typeof _ReportLeadsEp;
export type ReportLeadsInputType = NonNullable<_ReportLeadsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportLeadsCfg['execute']>[0]['input'];
export type ReportLeadsOutputType = Awaited<ReturnType<_ReportLeadsCfg['execute']>>;
export const reportLeads = createCaller<ReportLeadsInputType, ReportLeadsOutputType>('reportLeads');

type _ReportPipelineCfg = typeof _ReportPipelineEp;
export type ReportPipelineInputType = NonNullable<_ReportPipelineCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportPipelineCfg['execute']>[0]['input'];
export type ReportPipelineOutputType = Awaited<ReturnType<_ReportPipelineCfg['execute']>>;
export const reportPipeline = createCaller<ReportPipelineInputType, ReportPipelineOutputType>('reportPipeline');

type _ReportTeamCfg = typeof _ReportTeamEp;
export type ReportTeamInputType = NonNullable<_ReportTeamCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportTeamCfg['execute']>[0]['input'];
export type ReportTeamOutputType = Awaited<ReturnType<_ReportTeamCfg['execute']>>;
export const reportTeam = createCaller<ReportTeamInputType, ReportTeamOutputType>('reportTeam');

type _RunAutomationNowCfg = typeof _RunAutomationNowEp;
export type RunAutomationNowInputType = NonNullable<_RunAutomationNowCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RunAutomationNowCfg['execute']>[0]['input'];
export type RunAutomationNowOutputType = Awaited<ReturnType<_RunAutomationNowCfg['execute']>>;
export const runAutomationNow = createCaller<RunAutomationNowInputType, RunAutomationNowOutputType>('runAutomationNow');

type _RunSequencesCfg = typeof _RunSequencesEp;
export type RunSequencesInputType = NonNullable<_RunSequencesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RunSequencesCfg['execute']>[0]['input'];
export type RunSequencesOutputType = Awaited<ReturnType<_RunSequencesCfg['execute']>>;
export const runSequences = createCaller<RunSequencesInputType, RunSequencesOutputType>('runSequences');

type _SaveAutomationCfg = typeof _SaveAutomationEp;
export type SaveAutomationInputType = NonNullable<_SaveAutomationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveAutomationCfg['execute']>[0]['input'];
export type SaveAutomationOutputType = Awaited<ReturnType<_SaveAutomationCfg['execute']>>;
export const saveAutomation = createCaller<SaveAutomationInputType, SaveAutomationOutputType>('saveAutomation');

type _SaveBookingPageCfg = typeof _SaveBookingPageEp;
export type SaveBookingPageInputType = NonNullable<_SaveBookingPageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveBookingPageCfg['execute']>[0]['input'];
export type SaveBookingPageOutputType = Awaited<ReturnType<_SaveBookingPageCfg['execute']>>;
export const saveBookingPage = createCaller<SaveBookingPageInputType, SaveBookingPageOutputType>('saveBookingPage');

type _SaveChoiceCfg = typeof _SaveChoiceEp;
export type SaveChoiceInputType = NonNullable<_SaveChoiceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveChoiceCfg['execute']>[0]['input'];
export type SaveChoiceOutputType = Awaited<ReturnType<_SaveChoiceCfg['execute']>>;
export const saveChoice = createCaller<SaveChoiceInputType, SaveChoiceOutputType>('saveChoice');

type _SaveCustomFieldCfg = typeof _SaveCustomFieldEp;
export type SaveCustomFieldInputType = NonNullable<_SaveCustomFieldCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveCustomFieldCfg['execute']>[0]['input'];
export type SaveCustomFieldOutputType = Awaited<ReturnType<_SaveCustomFieldCfg['execute']>>;
export const saveCustomField = createCaller<SaveCustomFieldInputType, SaveCustomFieldOutputType>('saveCustomField');

type _SaveDocumentCfg = typeof _SaveDocumentEp;
export type SaveDocumentInputType = NonNullable<_SaveDocumentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveDocumentCfg['execute']>[0]['input'];
export type SaveDocumentOutputType = Awaited<ReturnType<_SaveDocumentCfg['execute']>>;
export const saveDocument = createCaller<SaveDocumentInputType, SaveDocumentOutputType>('saveDocument');

type _SaveFormCfg = typeof _SaveFormEp;
export type SaveFormInputType = NonNullable<_SaveFormCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveFormCfg['execute']>[0]['input'];
export type SaveFormOutputType = Awaited<ReturnType<_SaveFormCfg['execute']>>;
export const saveForm = createCaller<SaveFormInputType, SaveFormOutputType>('saveForm');

type _SaveLineItemsCfg = typeof _SaveLineItemsEp;
export type SaveLineItemsInputType = NonNullable<_SaveLineItemsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveLineItemsCfg['execute']>[0]['input'];
export type SaveLineItemsOutputType = Awaited<ReturnType<_SaveLineItemsCfg['execute']>>;
export const saveLineItems = createCaller<SaveLineItemsInputType, SaveLineItemsOutputType>('saveLineItems');

type _SaveMemberCfg = typeof _SaveMemberEp;
export type SaveMemberInputType = NonNullable<_SaveMemberCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveMemberCfg['execute']>[0]['input'];
export type SaveMemberOutputType = Awaited<ReturnType<_SaveMemberCfg['execute']>>;
export const saveMember = createCaller<SaveMemberInputType, SaveMemberOutputType>('saveMember');

type _SavePipelineCfg = typeof _SavePipelineEp;
export type SavePipelineInputType = NonNullable<_SavePipelineCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SavePipelineCfg['execute']>[0]['input'];
export type SavePipelineOutputType = Awaited<ReturnType<_SavePipelineCfg['execute']>>;
export const savePipeline = createCaller<SavePipelineInputType, SavePipelineOutputType>('savePipeline');

type _SaveProductCfg = typeof _SaveProductEp;
export type SaveProductInputType = NonNullable<_SaveProductCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveProductCfg['execute']>[0]['input'];
export type SaveProductOutputType = Awaited<ReturnType<_SaveProductCfg['execute']>>;
export const saveProduct = createCaller<SaveProductInputType, SaveProductOutputType>('saveProduct');

type _SaveQuotaCfg = typeof _SaveQuotaEp;
export type SaveQuotaInputType = NonNullable<_SaveQuotaCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveQuotaCfg['execute']>[0]['input'];
export type SaveQuotaOutputType = Awaited<ReturnType<_SaveQuotaCfg['execute']>>;
export const saveQuota = createCaller<SaveQuotaInputType, SaveQuotaOutputType>('saveQuota');

type _SaveQuoteCfg = typeof _SaveQuoteEp;
export type SaveQuoteInputType = NonNullable<_SaveQuoteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveQuoteCfg['execute']>[0]['input'];
export type SaveQuoteOutputType = Awaited<ReturnType<_SaveQuoteCfg['execute']>>;
export const saveQuote = createCaller<SaveQuoteInputType, SaveQuoteOutputType>('saveQuote');

type _SaveSequenceCfg = typeof _SaveSequenceEp;
export type SaveSequenceInputType = NonNullable<_SaveSequenceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveSequenceCfg['execute']>[0]['input'];
export type SaveSequenceOutputType = Awaited<ReturnType<_SaveSequenceCfg['execute']>>;
export const saveSequence = createCaller<SaveSequenceInputType, SaveSequenceOutputType>('saveSequence');

type _SaveStageCfg = typeof _SaveStageEp;
export type SaveStageInputType = NonNullable<_SaveStageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveStageCfg['execute']>[0]['input'];
export type SaveStageOutputType = Awaited<ReturnType<_SaveStageCfg['execute']>>;
export const saveStage = createCaller<SaveStageInputType, SaveStageOutputType>('saveStage');

type _SaveTagCfg = typeof _SaveTagEp;
export type SaveTagInputType = NonNullable<_SaveTagCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTagCfg['execute']>[0]['input'];
export type SaveTagOutputType = Awaited<ReturnType<_SaveTagCfg['execute']>>;
export const saveTag = createCaller<SaveTagInputType, SaveTagOutputType>('saveTag');

type _SaveTeamCfg = typeof _SaveTeamEp;
export type SaveTeamInputType = NonNullable<_SaveTeamCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTeamCfg['execute']>[0]['input'];
export type SaveTeamOutputType = Awaited<ReturnType<_SaveTeamCfg['execute']>>;
export const saveTeam = createCaller<SaveTeamInputType, SaveTeamOutputType>('saveTeam');

type _SaveTemplateCfg = typeof _SaveTemplateEp;
export type SaveTemplateInputType = NonNullable<_SaveTemplateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTemplateCfg['execute']>[0]['input'];
export type SaveTemplateOutputType = Awaited<ReturnType<_SaveTemplateCfg['execute']>>;
export const saveTemplate = createCaller<SaveTemplateInputType, SaveTemplateOutputType>('saveTemplate');

type _SaveViewCfg = typeof _SaveViewEp;
export type SaveViewInputType = NonNullable<_SaveViewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveViewCfg['execute']>[0]['input'];
export type SaveViewOutputType = Awaited<ReturnType<_SaveViewCfg['execute']>>;
export const saveView = createCaller<SaveViewInputType, SaveViewOutputType>('saveView');

type _SearchCfg = typeof _SearchEp;
export type SearchInputType = NonNullable<_SearchCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SearchCfg['execute']>[0]['input'];
export type SearchOutputType = Awaited<ReturnType<_SearchCfg['execute']>>;
export const search = createCaller<SearchInputType, SearchOutputType>('search');

type _SeedWorkspaceCfg = typeof _SeedWorkspaceEp;
export type SeedWorkspaceInputType = NonNullable<_SeedWorkspaceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SeedWorkspaceCfg['execute']>[0]['input'];
export type SeedWorkspaceOutputType = Awaited<ReturnType<_SeedWorkspaceCfg['execute']>>;
export const seedWorkspace = createCaller<SeedWorkspaceInputType, SeedWorkspaceOutputType>('seedWorkspace');

type _SendDigestCfg = typeof _SendDigestEp;
export type SendDigestInputType = NonNullable<_SendDigestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendDigestCfg['execute']>[0]['input'];
export type SendDigestOutputType = Awaited<ReturnType<_SendDigestCfg['execute']>>;
export const sendDigest = createCaller<SendDigestInputType, SendDigestOutputType>('sendDigest');

type _SendEmailCfg = typeof _SendEmailEp;
export type SendEmailInputType = NonNullable<_SendEmailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendEmailCfg['execute']>[0]['input'];
export type SendEmailOutputType = Awaited<ReturnType<_SendEmailCfg['execute']>>;
export const sendEmail = createCaller<SendEmailInputType, SendEmailOutputType>('sendEmail');

type _SendQuoteCfg = typeof _SendQuoteEp;
export type SendQuoteInputType = NonNullable<_SendQuoteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendQuoteCfg['execute']>[0]['input'];
export type SendQuoteOutputType = Awaited<ReturnType<_SendQuoteCfg['execute']>>;
export const sendQuote = createCaller<SendQuoteInputType, SendQuoteOutputType>('sendQuote');

type _SetDealContactsCfg = typeof _SetDealContactsEp;
export type SetDealContactsInputType = NonNullable<_SetDealContactsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetDealContactsCfg['execute']>[0]['input'];
export type SetDealContactsOutputType = Awaited<ReturnType<_SetDealContactsCfg['execute']>>;
export const setDealContacts = createCaller<SetDealContactsInputType, SetDealContactsOutputType>('setDealContacts');

type _SweepStalledDealsCfg = typeof _SweepStalledDealsEp;
export type SweepStalledDealsInputType = NonNullable<_SweepStalledDealsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SweepStalledDealsCfg['execute']>[0]['input'];
export type SweepStalledDealsOutputType = Awaited<ReturnType<_SweepStalledDealsCfg['execute']>>;
export const sweepStalledDeals = createCaller<SweepStalledDealsInputType, SweepStalledDealsOutputType>('sweepStalledDeals');

type _UndoImportCfg = typeof _UndoImportEp;
export type UndoImportInputType = NonNullable<_UndoImportCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UndoImportCfg['execute']>[0]['input'];
export type UndoImportOutputType = Awaited<ReturnType<_UndoImportCfg['execute']>>;
export const undoImport = createCaller<UndoImportInputType, UndoImportOutputType>('undoImport');

type _UpdateActivityCfg = typeof _UpdateActivityEp;
export type UpdateActivityInputType = NonNullable<_UpdateActivityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateActivityCfg['execute']>[0]['input'];
export type UpdateActivityOutputType = Awaited<ReturnType<_UpdateActivityCfg['execute']>>;
export const updateActivity = createCaller<UpdateActivityInputType, UpdateActivityOutputType>('updateActivity');

type _UpdateCompaniesCfg = typeof _UpdateCompaniesEp;
export type UpdateCompaniesInputType = NonNullable<_UpdateCompaniesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateCompaniesCfg['execute']>[0]['input'];
export type UpdateCompaniesOutputType = Awaited<ReturnType<_UpdateCompaniesCfg['execute']>>;
export const updateCompanies = createCaller<UpdateCompaniesInputType, UpdateCompaniesOutputType>('updateCompanies');

type _UpdateContactsCfg = typeof _UpdateContactsEp;
export type UpdateContactsInputType = NonNullable<_UpdateContactsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateContactsCfg['execute']>[0]['input'];
export type UpdateContactsOutputType = Awaited<ReturnType<_UpdateContactsCfg['execute']>>;
export const updateContacts = createCaller<UpdateContactsInputType, UpdateContactsOutputType>('updateContacts');

type _UpdateDealsCfg = typeof _UpdateDealsEp;
export type UpdateDealsInputType = NonNullable<_UpdateDealsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateDealsCfg['execute']>[0]['input'];
export type UpdateDealsOutputType = Awaited<ReturnType<_UpdateDealsCfg['execute']>>;
export const updateDeals = createCaller<UpdateDealsInputType, UpdateDealsOutputType>('updateDeals');

type _UpdateEnrollmentsCfg = typeof _UpdateEnrollmentsEp;
export type UpdateEnrollmentsInputType = NonNullable<_UpdateEnrollmentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateEnrollmentsCfg['execute']>[0]['input'];
export type UpdateEnrollmentsOutputType = Awaited<ReturnType<_UpdateEnrollmentsCfg['execute']>>;
export const updateEnrollments = createCaller<UpdateEnrollmentsInputType, UpdateEnrollmentsOutputType>('updateEnrollments');

type _UpdateLeadsCfg = typeof _UpdateLeadsEp;
export type UpdateLeadsInputType = NonNullable<_UpdateLeadsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateLeadsCfg['execute']>[0]['input'];
export type UpdateLeadsOutputType = Awaited<ReturnType<_UpdateLeadsCfg['execute']>>;
export const updateLeads = createCaller<UpdateLeadsInputType, UpdateLeadsOutputType>('updateLeads');

type _UpdateOrgSettingsCfg = typeof _UpdateOrgSettingsEp;
export type UpdateOrgSettingsInputType = NonNullable<_UpdateOrgSettingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateOrgSettingsCfg['execute']>[0]['input'];
export type UpdateOrgSettingsOutputType = Awaited<ReturnType<_UpdateOrgSettingsCfg['execute']>>;
export const updateOrgSettings = createCaller<UpdateOrgSettingsInputType, UpdateOrgSettingsOutputType>('updateOrgSettings');

type _UpdateProfileCfg = typeof _UpdateProfileEp;
export type UpdateProfileInputType = NonNullable<_UpdateProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateProfileCfg['execute']>[0]['input'];
export type UpdateProfileOutputType = Awaited<ReturnType<_UpdateProfileCfg['execute']>>;
export const updateProfile = createCaller<UpdateProfileInputType, UpdateProfileOutputType>('updateProfile');

type _UpdateTasksCfg = typeof _UpdateTasksEp;
export type UpdateTasksInputType = NonNullable<_UpdateTasksCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateTasksCfg['execute']>[0]['input'];
export type UpdateTasksOutputType = Awaited<ReturnType<_UpdateTasksCfg['execute']>>;
export const updateTasks = createCaller<UpdateTasksInputType, UpdateTasksOutputType>('updateTasks');

type _VoidQuoteCfg = typeof _VoidQuoteEp;
export type VoidQuoteInputType = NonNullable<_VoidQuoteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_VoidQuoteCfg['execute']>[0]['input'];
export type VoidQuoteOutputType = Awaited<ReturnType<_VoidQuoteCfg['execute']>>;
export const voidQuote = createCaller<VoidQuoteInputType, VoidQuoteOutputType>('voidQuote');


export const api = {
  aiDealBrief,
  aiDraftEmail,
  aiNextSteps,
  bootstrap,
  clearDemoData,
  convertLead,
  createCompany,
  createContact,
  createDeal,
  createLead,
  createTask,
  deactivateMember,
  deleteActivity,
  deleteAutomation,
  deleteBookingPage,
  deleteChoice,
  deleteCompanies,
  deleteContacts,
  deleteCustomField,
  deleteDeals,
  deleteDocument,
  deleteForm,
  deleteLeads,
  deleteProduct,
  deleteSequence,
  deleteStage,
  deleteTag,
  deleteTasks,
  deleteTeam,
  deleteTemplate,
  deleteView,
  duplicateQuote,
  enrollInSequence,
  exportRecords,
  findDuplicates,
  getBookingPage,
  getCompany,
  getContact,
  getDeal,
  getForm,
  getHome,
  getLead,
  getPipelineDetail,
  getQuote,
  getSequence,
  getTimeline,
  importRecords,
  listActivities,
  listAutomationRuns,
  listAutomations,
  listBookingPages,
  listBookings,
  listCompanies,
  listContacts,
  listDeals,
  listDocuments,
  listEnrollments,
  listForms,
  listImports,
  listLeads,
  listLineItems,
  listNotifications,
  listProducts,
  listQuotas,
  listQuotes,
  listSequences,
  listSubmissions,
  listTasks,
  listTemplates,
  logActivity,
  markNotifications,
  mergeRecords,
  quotePdf,
  reorderStages,
  reportActivity,
  reportForecast,
  reportLeads,
  reportPipeline,
  reportTeam,
  runAutomationNow,
  runSequences,
  saveAutomation,
  saveBookingPage,
  saveChoice,
  saveCustomField,
  saveDocument,
  saveForm,
  saveLineItems,
  saveMember,
  savePipeline,
  saveProduct,
  saveQuota,
  saveQuote,
  saveSequence,
  saveStage,
  saveTag,
  saveTeam,
  saveTemplate,
  saveView,
  search,
  seedWorkspace,
  sendDigest,
  sendEmail,
  sendQuote,
  setDealContacts,
  sweepStalledDeals,
  undoImport,
  updateActivity,
  updateCompanies,
  updateContacts,
  updateDeals,
  updateEnrollments,
  updateLeads,
  updateOrgSettings,
  updateProfile,
  updateTasks,
  voidQuote,
};
