import { lazy, Suspense, useEffect, useState } from 'react';
import { HashRouter, Navigate, Route, Routes, useLocation } from 'react-router-dom';
import { Toaster } from 'sonner';
import { initTheme } from './lib/theme';
import { AppShell } from './shell/AppShell';
import { RouteBoundary } from './shell/RouteBoundary';
import { ListSkeleton, Skeleton } from './ui/Layout';

/** Phones put toasts at the top: the bulk bar owns the bottom of the screen. */
function useToastPosition() {
  const [narrow, setNarrow] = useState(() => (typeof window === 'undefined' ? false : window.matchMedia('(max-width: 639px)').matches));
  useEffect(() => {
    const query = window.matchMedia('(max-width: 639px)');
    const update = () => setNarrow(query.matches);
    query.addEventListener('change', update);
    return () => query.removeEventListener('change', update);
  }, []);
  return narrow ? ('top-center' as const) : ('bottom-right' as const);
}

// Paint the stored (or system) theme before the first render — main.tsx is
// generated by the platform, so the app's own entry point is where this lives.
initTheme();

/**
 * Routes. Every page is lazy, so one page failing to compile can't take the
 * whole app down — and the first load stays small.
 */
const page = <T extends string>(loader: () => Promise<Record<string, unknown>>, name: T) => lazy(() => loader().then(m => ({ default: m[name] as React.ComponentType })));

const DealsPage = page(() => import('./features/deals/DealsPage'), 'DealsPage');
const QuotesPage = page(() => import('./features/quotes/QuotesPage'), 'QuotesPage');
const QuoteEditorPage = page(() => import('./features/quotes/QuoteEditorPage'), 'QuoteEditorPage');
const DealPage = page(() => import('./features/deals/DealPage'), 'DealPage');
const HomePage = page(() => import('./features/home/HomePage'), 'HomePage');
const InboxPage = page(() => import('./features/inbox/InboxPage'), 'InboxPage');
const LeadsPage = page(() => import('./features/leads/LeadsPage'), 'LeadsPage');
const LeadReviewPage = page(() => import('./features/leads/LeadReviewPage'), 'LeadReviewPage');
const LeadPage = page(() => import('./features/leads/LeadPage'), 'LeadPage');
const CompaniesPage = page(() => import('./features/companies/CompaniesPage'), 'CompaniesPage');
const CompanyPage = page(() => import('./features/companies/CompanyPage'), 'CompanyPage');
const ContactsPage = page(() => import('./features/contacts/ContactsPage'), 'ContactsPage');
const ContactPage = page(() => import('./features/contacts/ContactPage'), 'ContactPage');
const TasksPage = page(() => import('./features/tasks/TasksPage'), 'TasksPage');
const MeetingsPage = page(() => import('./features/tasks/MeetingsPage'), 'MeetingsPage');
const ActivityLogPage = page(() => import('./features/tasks/ActivityLogPage'), 'ActivityLogPage');
const ReportsPage = page(() => import('./features/reports/ReportsPage'), 'ReportsPage');
const MeetingLinksPage = page(() => import('./features/meetings/MeetingLinksPage'), 'MeetingLinksPage');
const MeetingLinkPage = page(() => import('./features/meetings/MeetingLinkPage'), 'MeetingLinkPage');
const FormsPage = page(() => import('./features/forms/FormsPage'), 'FormsPage');
const FormEditorPage = page(() => import('./features/forms/FormEditorPage'), 'FormEditorPage');
const SequencesPage = page(() => import('./features/outreach/SequencesPage'), 'SequencesPage');
const SequencePage = page(() => import('./features/outreach/SequencePage'), 'SequencePage');
const TemplatesPage = page(() => import('./features/outreach/TemplatesPage'), 'TemplatesPage');
const SettingsPage = page(() => import('./features/settings/SettingsPage'), 'SettingsPage');

/** Every navigation starts at the top of the page, not where the last one left off. */
function ScrollToTop() {
  const { pathname } = useLocation();
  useEffect(() => {
    document.getElementById('main')?.scrollTo({ top: 0 });
  }, [pathname]);
  return null;
}

/** What a page looks like for the moment before it arrives. */
function PageFallback() {
  return (
    <div className="flex flex-col">
      <div className="px-5 pt-6 sm:px-8">
        <Skeleton className="h-4 w-28" />
        <Skeleton className="mt-3 h-8 w-64" />
        <Skeleton className="mt-3 h-4 w-96" />
      </div>
      <ListSkeleton rows={6} className="mt-6" />
    </div>
  );
}

function Placeholder({ title }: { title: string }) {
  return (
    <div className="px-5 py-10 sm:px-8">
      <h1 className="font-display text-display text-ink">{title}</h1>
      <p className="mt-2 text-body text-ink-2">This area is being built.</p>
    </div>
  );
}

export default function App() {
  const toastPosition = useToastPosition();
  return (
    <HashRouter>
      <AppShell>
        <ScrollToTop />
        <Pages />
      </AppShell>
      <Toaster position={toastPosition} offset={16} toastOptions={{ duration: 4500 }} />
    </HashRouter>
  );
}

function Pages() {
  const { pathname } = useLocation();
  return (
    <RouteBoundary routeKey={pathname}>
      <Suspense fallback={<PageFallback />}>
        <Routes>
            <Route path="/" element={<Navigate to="/home" replace />} />
            <Route path="/home" element={<HomePage />} />
            <Route path="/inbox" element={<InboxPage />} />
            <Route path="/leads" element={<LeadsPage />} />
            <Route path="/leads/review" element={<LeadReviewPage />} />
            <Route path="/leads/:id" element={<LeadPage />} />
            <Route path="/deals" element={<DealsPage />} />
            <Route path="/deals/:id" element={<DealPage />} />
            <Route path="/companies" element={<CompaniesPage />} />
            <Route path="/companies/:id" element={<CompanyPage />} />
            <Route path="/companies/:id/:tab" element={<CompanyPage />} />
            <Route path="/contacts" element={<ContactsPage />} />
            <Route path="/contacts/:id" element={<ContactPage />} />
            <Route path="/contacts/:id/:tab" element={<ContactPage />} />
            <Route path="/tasks" element={<TasksPage />} />
            <Route path="/tasks/meetings" element={<MeetingsPage />} />
            <Route path="/tasks/activity" element={<ActivityLogPage />} />
            {/* The four outreach surfaces each carry the same tab row in their header. */}
            <Route path="/outreach" element={<Navigate to="/outreach/sequences" replace />} />
            <Route path="/outreach/sequences" element={<SequencesPage />} />
            <Route path="/outreach/sequences/:id" element={<SequencePage />} />
            <Route path="/outreach/templates" element={<TemplatesPage />} />
            <Route path="/outreach/forms" element={<FormsPage />} />
            <Route path="/outreach/forms/:id" element={<FormEditorPage />} />
            <Route path="/outreach/meetings" element={<MeetingLinksPage />} />
            <Route path="/outreach/meetings/:id" element={<MeetingLinkPage />} />
            <Route path="/outreach/*" element={<Placeholder title="Outreach" />} />
            <Route path="/reports/*" element={<ReportsPage />} />
            <Route path="/settings" element={<Navigate to="/settings/profile" replace />} />
            <Route path="/settings/:section" element={<SettingsPage />} />
            {/* /quotes/new is handled by the editor itself. */}
            <Route path="/quotes" element={<QuotesPage />} />
            <Route path="/quotes/:id" element={<QuoteEditorPage />} />
            <Route path="*" element={<Navigate to="/home" replace />} />
        </Routes>
      </Suspense>
    </RouteBoundary>
  );
}
