// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _BookMeetingEp } from '../src/api/bookMeeting';
import type { default as _GetAvailabilityEp } from '../src/api/getAvailability';
import type { default as _GetMeetingPageEp } from '../src/api/getMeetingPage';
import type { default as _GetPublicFormEp } from '../src/api/getPublicForm';
import type { default as _GetPublicOrgEp } from '../src/api/getPublicOrg';
import type { default as _GetPublicQuoteEp } from '../src/api/getPublicQuote';
import type { default as _GetUnsubscribeEp } from '../src/api/getUnsubscribe';
import type { default as _ManageBookingEp } from '../src/api/manageBooking';
import type { default as _RespondToQuoteEp } from '../src/api/respondToQuote';
import type { default as _SetUnsubscribeEp } from '../src/api/setUnsubscribe';
import type { default as _SubmitFormEp } from '../src/api/submitForm';

type _BookMeetingCfg = typeof _BookMeetingEp;
export type BookMeetingInputType = NonNullable<_BookMeetingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BookMeetingCfg['execute']>[0]['input'];
export type BookMeetingOutputType = Awaited<ReturnType<_BookMeetingCfg['execute']>>;
export const bookMeeting = createCaller<BookMeetingInputType, BookMeetingOutputType>('bookMeeting');

type _GetAvailabilityCfg = typeof _GetAvailabilityEp;
export type GetAvailabilityInputType = NonNullable<_GetAvailabilityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAvailabilityCfg['execute']>[0]['input'];
export type GetAvailabilityOutputType = Awaited<ReturnType<_GetAvailabilityCfg['execute']>>;
export const getAvailability = createCaller<GetAvailabilityInputType, GetAvailabilityOutputType>('getAvailability');

type _GetMeetingPageCfg = typeof _GetMeetingPageEp;
export type GetMeetingPageInputType = NonNullable<_GetMeetingPageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMeetingPageCfg['execute']>[0]['input'];
export type GetMeetingPageOutputType = Awaited<ReturnType<_GetMeetingPageCfg['execute']>>;
export const getMeetingPage = createCaller<GetMeetingPageInputType, GetMeetingPageOutputType>('getMeetingPage');

type _GetPublicFormCfg = typeof _GetPublicFormEp;
export type GetPublicFormInputType = NonNullable<_GetPublicFormCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPublicFormCfg['execute']>[0]['input'];
export type GetPublicFormOutputType = Awaited<ReturnType<_GetPublicFormCfg['execute']>>;
export const getPublicForm = createCaller<GetPublicFormInputType, GetPublicFormOutputType>('getPublicForm');

type _GetPublicOrgCfg = typeof _GetPublicOrgEp;
export type GetPublicOrgInputType = NonNullable<_GetPublicOrgCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPublicOrgCfg['execute']>[0]['input'];
export type GetPublicOrgOutputType = Awaited<ReturnType<_GetPublicOrgCfg['execute']>>;
export const getPublicOrg = createCaller<GetPublicOrgInputType, GetPublicOrgOutputType>('getPublicOrg');

type _GetPublicQuoteCfg = typeof _GetPublicQuoteEp;
export type GetPublicQuoteInputType = NonNullable<_GetPublicQuoteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPublicQuoteCfg['execute']>[0]['input'];
export type GetPublicQuoteOutputType = Awaited<ReturnType<_GetPublicQuoteCfg['execute']>>;
export const getPublicQuote = createCaller<GetPublicQuoteInputType, GetPublicQuoteOutputType>('getPublicQuote');

type _GetUnsubscribeCfg = typeof _GetUnsubscribeEp;
export type GetUnsubscribeInputType = NonNullable<_GetUnsubscribeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetUnsubscribeCfg['execute']>[0]['input'];
export type GetUnsubscribeOutputType = Awaited<ReturnType<_GetUnsubscribeCfg['execute']>>;
export const getUnsubscribe = createCaller<GetUnsubscribeInputType, GetUnsubscribeOutputType>('getUnsubscribe');

type _ManageBookingCfg = typeof _ManageBookingEp;
export type ManageBookingInputType = NonNullable<_ManageBookingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ManageBookingCfg['execute']>[0]['input'];
export type ManageBookingOutputType = Awaited<ReturnType<_ManageBookingCfg['execute']>>;
export const manageBooking = createCaller<ManageBookingInputType, ManageBookingOutputType>('manageBooking');

type _RespondToQuoteCfg = typeof _RespondToQuoteEp;
export type RespondToQuoteInputType = NonNullable<_RespondToQuoteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RespondToQuoteCfg['execute']>[0]['input'];
export type RespondToQuoteOutputType = Awaited<ReturnType<_RespondToQuoteCfg['execute']>>;
export const respondToQuote = createCaller<RespondToQuoteInputType, RespondToQuoteOutputType>('respondToQuote');

type _SetUnsubscribeCfg = typeof _SetUnsubscribeEp;
export type SetUnsubscribeInputType = NonNullable<_SetUnsubscribeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetUnsubscribeCfg['execute']>[0]['input'];
export type SetUnsubscribeOutputType = Awaited<ReturnType<_SetUnsubscribeCfg['execute']>>;
export const setUnsubscribe = createCaller<SetUnsubscribeInputType, SetUnsubscribeOutputType>('setUnsubscribe');

type _SubmitFormCfg = typeof _SubmitFormEp;
export type SubmitFormInputType = NonNullable<_SubmitFormCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitFormCfg['execute']>[0]['input'];
export type SubmitFormOutputType = Awaited<ReturnType<_SubmitFormCfg['execute']>>;
export const submitForm = createCaller<SubmitFormInputType, SubmitFormOutputType>('submitForm');


export const api = {
  bookMeeting,
  getAvailability,
  getMeetingPage,
  getPublicForm,
  getPublicOrg,
  getPublicQuote,
  getUnsubscribe,
  manageBooking,
  respondToQuote,
  setUnsubscribe,
  submitForm,
};
