#!/usr/bin/env node
/**
 * The finish-pass audit: the things a type-check can never catch, because they
 * are features that exist in the backend and cannot be reached from the UI.
 *
 *   node scripts/audit.mjs
 *
 * It reports:
 *   1. endpoints no frontend file calls
 *   2. filter/input keys no UI ever sets
 *   3. <Link to="…"> targets with no matching route
 *   4. create-dialog kinds that aren't registered
 *   5. TODO/FIXME left behind, and any lucide/@project/components imports
 *
 * Every finding is a lead, not a verdict: an endpoint called only by another
 * endpoint, or a filter set by a saved view, is fine. Check before deleting.
 */
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(new URL('..', import.meta.url).pathname);
const apps = ['apps/crm', 'apps/crm-pages'];

const walk = (dir, out = []) => {
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === '.zite' || entry.name === 'dist') continue;
      walk(full, out);
    } else if (/\.(ts|tsx)$/.test(entry.name)) out.push(full);
  }
  return out;
};

let findings = 0;
const report = (title, items, hint) => {
  if (!items.length) return;
  findings += items.length;
  console.log(`\n${title} (${items.length})`);
  if (hint) console.log(`  ${hint}`);
  for (const item of items) console.log(`  - ${item}`);
};

for (const app of apps) {
  const appDir = path.join(root, app);
  if (!fs.existsSync(appDir)) continue;
  const apiDir = path.join(appDir, 'src/api');
  const endpoints = fs.existsSync(apiDir) ? fs.readdirSync(apiDir).filter(f => f.endsWith('.ts')).map(f => f.replace(/\.ts$/, '')) : [];
  // main.tsx is generated by the platform — its lucide import isn't ours to fix.
  const frontendFiles = walk(path.join(appDir, 'src')).filter(f => !f.includes(`${path.sep}api${path.sep}`) && !f.endsWith(`${path.sep}main.tsx`));
  const frontend = frontendFiles.map(f => fs.readFileSync(f, 'utf8')).join('\n');
  const serverText = endpoints.map(name => fs.readFileSync(path.join(apiDir, `${name}.ts`), 'utf8')).join('\n');

  console.log(`\n=== ${app}`);
  console.log(`  ${endpoints.length} endpoints, ${frontendFiles.length} frontend files`);

  // 1. Endpoints nothing calls.
  const unused = endpoints.filter(name => {
    const re = new RegExp(`\\b${name}\\b`);
    if (re.test(frontend)) return false;
    // A scheduled endpoint, or one another endpoint calls, is fine.
    const source = fs.readFileSync(path.join(apiDir, `${name}.ts`), 'utf8');
    if (/schedule:\s*{/.test(source)) return false;
    return !new RegExp(`\\b${name}\\b`).test(serverText.replace(source, ''));
  });
  report('Endpoints no UI calls', unused.filter(n => !/^zz/i.test(n)), 'Each one is either dead code or a missing button.');
  report('Debug endpoints — must not ship', endpoints.filter(n => /^zz|debug/i.test(n)), 'Harness helpers. Delete before committing.');

  // Every endpoint must re-parse its input: Zite does not enforce inputSchema.
  const unparsed = endpoints.filter(name => {
    const source = fs.readFileSync(path.join(apiDir, `${name}.ts`), 'utf8');
    return !/parseInput\(/.test(source) && /inputSchema:\s*z\.object\(\{\s*[a-zA-Z]/.test(source);
  });
  report('Endpoints that trust their input', unparsed, 'Zite does not enforce inputSchema — re-parse with parseInput inside execute.');

  // 2. Input keys no UI sets — read the filter schemas out of the endpoints.
  const unreachable = [];
  for (const name of endpoints) {
    const source = fs.readFileSync(path.join(apiDir, `${name}.ts`), 'utf8');
    const block = source.match(/const filters\s*=\s*z\.object\(\{([\s\S]*?)\n\}\)/) ?? source.match(/filterSchema\s*=\s*z\.object\(\{([\s\S]*?)\n\}\)/);
    if (!block) continue;
    for (const line of block[1].split('\n')) {
      const key = line.match(/^\s*([a-zA-Z][a-zA-Z0-9]*)\s*:/);
      if (!key) continue;
      if (!new RegExp(`\\b${key[1]}\\b`).test(frontend)) unreachable.push(`${name}.filters.${key[1]}`);
    }
  }
  report('Filters no UI can set', unreachable, 'A filter with no control is a feature nobody can use.');

  // 3. Links with no route.
  const routes = new Set();
  const appFile = path.join(appDir, 'src/App.tsx');
  if (fs.existsSync(appFile)) {
    for (const m of fs.readFileSync(appFile, 'utf8').matchAll(/path="([^"]+)"/g)) {
      routes.add(m[1].replace(/\/:.*$/, '').replace(/\/\*$/, '') || '/');
    }
  }
  const links = new Set();
  for (const m of frontend.matchAll(/to=["'`]\/([a-zA-Z0-9/_-]*)/g)) links.add(`/${m[1]}`);
  for (const m of frontend.matchAll(/navigate\(["'`]\/([a-zA-Z0-9/_-]*)/g)) links.add(`/${m[1]}`);
  const broken = [...links].filter(link => {
    const first = `/${link.split('/')[1] ?? ''}`;
    return !routes.has(link) && !routes.has(first) && ![...routes].some(r => r !== '/' && link.startsWith(r));
  });
  report('Links with no matching route', broken, 'These navigate to the catch-all instead.');

  // 4. Create dialogs referenced but not registered.
  const registry = fs.existsSync(path.join(appDir, 'src/shell/CreateDialogs.tsx')) ? fs.readFileSync(path.join(appDir, 'src/shell/CreateDialogs.tsx'), 'utf8') : '';
  if (registry) {
    const opened = new Set([...frontend.matchAll(/openCreate\(\s*['"]([a-zA-Z]+)['"]/g)].map(m => m[1]));
    const registered = new Set([...registry.matchAll(/^\s{2}([a-zA-Z]+):\s*lazy/gm)].map(m => m[1]));
    report('Create kinds opened but not registered', [...opened].filter(kind => !registered.has(kind)), 'These toast "not available" instead of opening.');
  }

  // 5. Things that shouldn't ship.
  const banned = [];
  for (const file of frontendFiles) {
    const source = fs.readFileSync(file, 'utf8');
    const rel = path.relative(root, file);
    if (/from ['"]lucide-react['"]/.test(source)) banned.push(`${rel}: imports lucide-react (use @phosphor-icons/react)`);
    if (/@project\/(components|ui)/.test(source)) banned.push(`${rel}: imports @project/components or @project/ui`);
    if (/text-(ink|foreground)\/[0-9]/.test(source)) banned.push(`${rel}: fades text with an opacity modifier (use ink-2/ink-3)`);
    if (/\btext-(gray|slate|zinc|amber|sky|emerald|rose|violet|indigo)-[0-9]/.test(source)) banned.push(`${rel}: raw Tailwind palette colour (use tokens)`);
    for (const m of source.matchAll(/(TODO|FIXME|XXX)[:\s]([^\n]{0,60})/g)) banned.push(`${rel}: ${m[1]} ${m[2].trim()}`);
  }
  report('Things that shouldn’t ship', banned);
}

console.log(findings ? `\n${findings} things to look at.` : '\nNothing to flag.');
