// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//     a filter value of `undefined` is REJECTED (it would query unfiltered
//       and match an arbitrary record). Check the value first.
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Members" table, as it is read back. */
export type MembersRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  email?: string;
  role?: "Admin" | "Manager" | "Rep" | "Viewer" | string;
  status?: "Active" | "Invited" | "Deactivated" | string;
  title?: string;
  teamId?: string;
  phone?: string;
  color?: string;
  avatarUrl?: string;
  timezone?: string;
  emailSignature?: string;
  preferences?: string;
  /** "Last Seen At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastSeenAt?: string;
};

/** What you may write when creating or updating a record in the "Members" table. */
export type MembersRecordInput = {
  name: string | null;
  email: string | null;
  role: "Admin" | "Manager" | "Rep" | "Viewer" | string | null;
  status: "Active" | "Invited" | "Deactivated" | string | null;
  title: string | null;
  teamId: string | null;
  phone: string | null;
  color: string | null;
  avatarUrl: string | null;
  timezone: string | null;
  emailSignature: string | null;
  preferences: string | null;
  lastSeenAt: string | Date | null;
};

/** A record in the "Teams" table, as it is read back. */
export type TeamsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  description?: string;
  leadId?: string;
  color?: string;
};

/** What you may write when creating or updating a record in the "Teams" table. */
export type TeamsRecordInput = {
  name: string | null;
  description: string | null;
  leadId: string | null;
  color: string | null;
};

/** A record in the "Companies" table, as it is read back. */
export type CompaniesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  domain?: string;
  website?: string;
  industry?: string;
  type?: "Prospect" | "Customer" | "Partner" | "Former Customer" | "Other" | string;
  /** "Employees". 0 decimal places, format: local (e.g. 1,000,000.50) */
  employees?: number;
  /** "Annual Revenue". Value is a raw number; display as currency with symbol "$", 0 decimal places, format: local (e.g. 1,000,000.50) */
  annualRevenue?: number;
  ownerId?: string;
  parentCompanyId?: string;
  phone?: string;
  linkedinUrl?: string;
  address?: string;
  city?: string;
  region?: string;
  postalCode?: string;
  country?: string;
  description?: string;
  source?: string;
  tagIds?: string;
  customFields?: string;
  logoUrl?: string;
  /** "Customer Since". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  customerSince?: string;
  /** "Last Activity At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastActivityAt?: string;
  archived?: boolean;
  importId?: string;
};

/** What you may write when creating or updating a record in the "Companies" table. */
export type CompaniesRecordInput = {
  name: string | null;
  domain: string | null;
  website: string | null;
  industry: string | null;
  type: "Prospect" | "Customer" | "Partner" | "Former Customer" | "Other" | string | null;
  employees: string | number | null;
  annualRevenue: string | number | null;
  ownerId: string | null;
  parentCompanyId: string | null;
  phone: string | null;
  linkedinUrl: string | null;
  address: string | null;
  city: string | null;
  region: string | null;
  postalCode: string | null;
  country: string | null;
  description: string | null;
  source: string | null;
  tagIds: string | null;
  customFields: string | null;
  logoUrl: string | null;
  customerSince: string | Date | null;
  lastActivityAt: string | Date | null;
  archived: string | boolean | null;
  importId: string | null;
};

/** A record in the "Contacts" table, as it is read back. */
export type ContactsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  mobile?: string;
  title?: string;
  companyId?: string;
  ownerId?: string;
  source?: string;
  linkedinUrl?: string;
  city?: string;
  country?: string;
  timezone?: string;
  background?: string;
  doNotContact?: boolean;
  /** "Unsubscribed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  unsubscribedAt?: string;
  unsubscribeToken?: string;
  tagIds?: string;
  customFields?: string;
  avatarUrl?: string;
  /** "Last Activity At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastActivityAt?: string;
  /** "Last Contacted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastContactedAt?: string;
  archived?: boolean;
  importId?: string;
};

/** What you may write when creating or updating a record in the "Contacts" table. */
export type ContactsRecordInput = {
  name: string | null;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
  phone: string | null;
  mobile: string | null;
  title: string | null;
  companyId: string | null;
  ownerId: string | null;
  source: string | null;
  linkedinUrl: string | null;
  city: string | null;
  country: string | null;
  timezone: string | null;
  background: string | null;
  doNotContact: string | boolean | null;
  unsubscribedAt: string | Date | null;
  unsubscribeToken: string | null;
  tagIds: string | null;
  customFields: string | null;
  avatarUrl: string | null;
  lastActivityAt: string | Date | null;
  lastContactedAt: string | Date | null;
  archived: string | boolean | null;
  importId: string | null;
};

/** A record in the "Leads" table, as it is read back. */
export type LeadsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  title?: string;
  companyName?: string;
  website?: string;
  /** "Employees". 0 decimal places, format: local (e.g. 1,000,000.50) */
  employees?: number;
  industry?: string;
  country?: string;
  source?: string;
  sourceDetail?: string;
  status?: "New" | "Working" | "Nurturing" | "Qualified" | "Disqualified" | string;
  /** "Score". 0 decimal places, format: local (e.g. 1,000,000.50) */
  score?: number;
  ownerId?: string;
  message?: string;
  disqualifyReason?: string;
  /** "Converted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  convertedAt?: string;
  convertedContactId?: string;
  convertedCompanyId?: string;
  convertedDealId?: string;
  formId?: string;
  utmSource?: string;
  utmMedium?: string;
  utmCampaign?: string;
  tagIds?: string;
  customFields?: string;
  /** "Received At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  receivedAt?: string;
  /** "First Response At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  firstResponseAt?: string;
  /** "Last Activity At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastActivityAt?: string;
  importId?: string;
};

/** What you may write when creating or updating a record in the "Leads" table. */
export type LeadsRecordInput = {
  name: string | null;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
  phone: string | null;
  title: string | null;
  companyName: string | null;
  website: string | null;
  employees: string | number | null;
  industry: string | null;
  country: string | null;
  source: string | null;
  sourceDetail: string | null;
  status: "New" | "Working" | "Nurturing" | "Qualified" | "Disqualified" | string | null;
  score: string | number | null;
  ownerId: string | null;
  message: string | null;
  disqualifyReason: string | null;
  convertedAt: string | Date | null;
  convertedContactId: string | null;
  convertedCompanyId: string | null;
  convertedDealId: string | null;
  formId: string | null;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  tagIds: string | null;
  customFields: string | null;
  receivedAt: string | Date | null;
  firstResponseAt: string | Date | null;
  lastActivityAt: string | Date | null;
  importId: string | null;
};

/** A record in the "Pipelines" table, as it is read back. */
export type PipelinesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  description?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  isDefault?: boolean;
  archived?: boolean;
};

/** What you may write when creating or updating a record in the "Pipelines" table. */
export type PipelinesRecordInput = {
  name: string | null;
  description: string | null;
  position: string | number | null;
  isDefault: string | boolean | null;
  archived: string | boolean | null;
};

/** A record in the "Stages" table, as it is read back. */
export type StagesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  pipelineId?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  /** "Probability". 0 decimal places, format: local (e.g. 1,000,000.50) */
  probability?: number;
  kind?: "Open" | "Won" | "Lost" | string;
  /** "Rotting Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  rottingDays?: number;
  guidance?: string;
  archived?: boolean;
};

/** What you may write when creating or updating a record in the "Stages" table. */
export type StagesRecordInput = {
  name: string | null;
  pipelineId: string | null;
  position: string | number | null;
  probability: string | number | null;
  kind: "Open" | "Won" | "Lost" | string | null;
  rottingDays: string | number | null;
  guidance: string | null;
  archived: string | boolean | null;
};

/** A record in the "Deals" table, as it is read back. */
export type DealsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  companyId?: string;
  contactId?: string;
  pipelineId?: string;
  stageId?: string;
  ownerId?: string;
  /** "Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  /** "Close Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  closeDate?: string;
  status?: "Open" | "Won" | "Lost" | string;
  /** "Probability". 0 decimal places, format: local (e.g. 1,000,000.50) */
  probability?: number;
  forecastCategory?: "Pipeline" | "Best Case" | "Commit" | "Closed" | "Omitted" | string;
  type?: "New Business" | "Expansion" | "Renewal" | string;
  source?: string;
  nextStep?: string;
  lostReason?: string;
  closeNote?: string;
  /** "Closed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  closedAt?: string;
  /** "Stage Entered At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  stageEnteredAt?: string;
  /** "Opened At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  openedAt?: string;
  /** "Position". 4 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  description?: string;
  tagIds?: string;
  customFields?: string;
  /** "Last Activity At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastActivityAt?: string;
  archived?: boolean;
  importId?: string;
};

/** What you may write when creating or updating a record in the "Deals" table. */
export type DealsRecordInput = {
  name: string | null;
  companyId: string | null;
  contactId: string | null;
  pipelineId: string | null;
  stageId: string | null;
  ownerId: string | null;
  amount: string | number | null;
  closeDate: string | Date | null;
  status: "Open" | "Won" | "Lost" | string | null;
  probability: string | number | null;
  forecastCategory: "Pipeline" | "Best Case" | "Commit" | "Closed" | "Omitted" | string | null;
  type: "New Business" | "Expansion" | "Renewal" | string | null;
  source: string | null;
  nextStep: string | null;
  lostReason: string | null;
  closeNote: string | null;
  closedAt: string | Date | null;
  stageEnteredAt: string | Date | null;
  openedAt: string | Date | null;
  position: string | number | null;
  description: string | null;
  tagIds: string | null;
  customFields: string | null;
  lastActivityAt: string | Date | null;
  archived: string | boolean | null;
  importId: string | null;
};

/** A record in the "Deal Contacts" table, as it is read back. */
export type DealContactsRecordType = {
  id: string;
  /** Primary field. "Deal Id" */
  dealId?: string;
  contactId?: string;
  role?: "Decision Maker" | "Economic Buyer" | "Champion" | "Influencer" | "Technical Evaluator" | "End User" | "Blocker" | "Other" | string;
};

/** What you may write when creating or updating a record in the "Deal Contacts" table. */
export type DealContactsRecordInput = {
  dealId: string | null;
  contactId: string | null;
  role: "Decision Maker" | "Economic Buyer" | "Champion" | "Influencer" | "Technical Evaluator" | "End User" | "Blocker" | "Other" | string | null;
};

/** A record in the "Stage Changes" table, as it is read back. */
export type StageChangesRecordType = {
  id: string;
  /** Primary field. "Deal Id" */
  dealId?: string;
  pipelineId?: string;
  fromStageId?: string;
  toStageId?: string;
  /** "Changed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  changedAt?: string;
  actorId?: string;
  /** "Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
};

/** What you may write when creating or updating a record in the "Stage Changes" table. */
export type StageChangesRecordInput = {
  dealId: string | null;
  pipelineId: string | null;
  fromStageId: string | null;
  toStageId: string | null;
  changedAt: string | Date | null;
  actorId: string | null;
  amount: string | number | null;
};

/** A record in the "Activities" table, as it is read back. */
export type ActivitiesRecordType = {
  id: string;
  /** Primary field. "Subject" */
  subject?: string;
  kind?: "Note" | "Call" | "Email" | "Meeting" | string;
  body?: string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
  /** "Ends At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  endsAt?: string;
  /** "Duration Minutes". 0 decimal places, format: local (e.g. 1,000,000.50) */
  durationMinutes?: number;
  outcome?: "Connected" | "Left Voicemail" | "No Answer" | "Busy" | "Wrong Number" | "Scheduled" | "Completed" | "No Show" | "Canceled" | string;
  direction?: "Outbound" | "Inbound" | string;
  emailFrom?: string;
  emailTo?: string;
  emailCc?: string;
  delivery?: "Sent" | "Logged" | "Failed" | "Not Sent" | string;
  location?: string;
  attendees?: string;
  ownerId?: string;
  companyId?: string;
  contactId?: string;
  dealId?: string;
  leadId?: string;
  enrollmentId?: string;
  bookingPageId?: string;
  publicToken?: string;
  pinned?: boolean;
  createdById?: string;
};

/** What you may write when creating or updating a record in the "Activities" table. */
export type ActivitiesRecordInput = {
  subject: string | null;
  kind: "Note" | "Call" | "Email" | "Meeting" | string | null;
  body: string | null;
  occurredAt: string | Date | null;
  endsAt: string | Date | null;
  durationMinutes: string | number | null;
  outcome: "Connected" | "Left Voicemail" | "No Answer" | "Busy" | "Wrong Number" | "Scheduled" | "Completed" | "No Show" | "Canceled" | string | null;
  direction: "Outbound" | "Inbound" | string | null;
  emailFrom: string | null;
  emailTo: string | null;
  emailCc: string | null;
  delivery: "Sent" | "Logged" | "Failed" | "Not Sent" | string | null;
  location: string | null;
  attendees: string | null;
  ownerId: string | null;
  companyId: string | null;
  contactId: string | null;
  dealId: string | null;
  leadId: string | null;
  enrollmentId: string | null;
  bookingPageId: string | null;
  publicToken: string | null;
  pinned: string | boolean | null;
  createdById: string | null;
};

/** A record in the "Tasks" table, as it is read back. */
export type TasksRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  type?: "To-do" | "Call" | "Email" | "Meeting" | "LinkedIn" | string;
  status?: "Open" | "Done" | string;
  priority?: "High" | "Normal" | "Low" | string;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  dueTime?: string;
  ownerId?: string;
  createdById?: string;
  companyId?: string;
  contactId?: string;
  dealId?: string;
  leadId?: string;
  notes?: string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
  enrollmentId?: string;
  stepId?: string;
  systemKey?: string;
  /** "Reminded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  remindedAt?: string;
};

/** What you may write when creating or updating a record in the "Tasks" table. */
export type TasksRecordInput = {
  title: string | null;
  type: "To-do" | "Call" | "Email" | "Meeting" | "LinkedIn" | string | null;
  status: "Open" | "Done" | string | null;
  priority: "High" | "Normal" | "Low" | string | null;
  dueDate: string | Date | null;
  dueTime: string | null;
  ownerId: string | null;
  createdById: string | null;
  companyId: string | null;
  contactId: string | null;
  dealId: string | null;
  leadId: string | null;
  notes: string | null;
  completedAt: string | Date | null;
  enrollmentId: string | null;
  stepId: string | null;
  systemKey: string | null;
  remindedAt: string | Date | null;
};

/** A record in the "Products" table, as it is read back. */
export type ProductsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  sku?: string;
  description?: string;
  /** "Unit Price". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  unitPrice?: number;
  billing?: "One-time" | "Monthly" | "Annual" | string;
  category?: string;
  active?: boolean;
};

/** What you may write when creating or updating a record in the "Products" table. */
export type ProductsRecordInput = {
  name: string | null;
  sku: string | null;
  description: string | null;
  unitPrice: string | number | null;
  billing: "One-time" | "Monthly" | "Annual" | string | null;
  category: string | null;
  active: string | boolean | null;
};

/** A record in the "Line Items" table, as it is read back. */
export type LineItemsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  dealId?: string;
  productId?: string;
  description?: string;
  /** "Quantity". 2 decimal places, format: local (e.g. 1,000,000.50) */
  quantity?: number;
  /** "Unit Price". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  unitPrice?: number;
  /** "Discount". 2 decimal places, format: local (e.g. 1,000,000.50) */
  discount?: number;
  billing?: "One-time" | "Monthly" | "Annual" | string;
  /** "Term Months". 0 decimal places, format: local (e.g. 1,000,000.50) */
  termMonths?: number;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Line Items" table. */
export type LineItemsRecordInput = {
  name: string | null;
  dealId: string | null;
  productId: string | null;
  description: string | null;
  quantity: string | number | null;
  unitPrice: string | number | null;
  discount: string | number | null;
  billing: "One-time" | "Monthly" | "Annual" | string | null;
  termMonths: string | number | null;
  position: string | number | null;
};

/** A record in the "Quotes" table, as it is read back. */
export type QuotesRecordType = {
  id: string;
  /** Primary field. "Number" */
  number?: string;
  title?: string;
  dealId?: string;
  companyId?: string;
  contactId?: string;
  ownerId?: string;
  status?: "Draft" | "Sent" | "Viewed" | "Accepted" | "Declined" | "Expired" | "Void" | string;
  token?: string;
  items?: string;
  /** "Subtotal". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  subtotal?: number;
  /** "Discount Total". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  discountTotal?: number;
  /** "Tax Rate". 3 decimal places, format: local (e.g. 1,000,000.50) */
  taxRate?: number;
  /** "Tax". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  tax?: number;
  /** "Total". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  total?: number;
  currency?: string;
  /** "Expires On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  expiresOn?: string;
  terms?: string;
  buyerNote?: string;
  /** "Sent At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  sentAt?: string;
  /** "Viewed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  viewedAt?: string;
  /** "View Count". 0 decimal places, format: local (e.g. 1,000,000.50) */
  viewCount?: number;
  /** "Accepted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  acceptedAt?: string;
  acceptedName?: string;
  acceptedTitle?: string;
  acceptedEmail?: string;
  /** "Declined At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  declinedAt?: string;
  declineReason?: string;
};

/** What you may write when creating or updating a record in the "Quotes" table. */
export type QuotesRecordInput = {
  number: string | null;
  title: string | null;
  dealId: string | null;
  companyId: string | null;
  contactId: string | null;
  ownerId: string | null;
  status: "Draft" | "Sent" | "Viewed" | "Accepted" | "Declined" | "Expired" | "Void" | string | null;
  token: string | null;
  items: string | null;
  subtotal: string | number | null;
  discountTotal: string | number | null;
  taxRate: string | number | null;
  tax: string | number | null;
  total: string | number | null;
  currency: string | null;
  expiresOn: string | Date | null;
  terms: string | null;
  buyerNote: string | null;
  sentAt: string | Date | null;
  viewedAt: string | Date | null;
  viewCount: string | number | null;
  acceptedAt: string | Date | null;
  acceptedName: string | null;
  acceptedTitle: string | null;
  acceptedEmail: string | null;
  declinedAt: string | Date | null;
  declineReason: string | null;
};

/** A record in the "Email Templates" table, as it is read back. */
export type EmailTemplatesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  subject?: string;
  body?: string;
  category?: string;
  ownerId?: string;
  shared?: boolean;
  archived?: boolean;
  /** "Use Count". 0 decimal places, format: local (e.g. 1,000,000.50) */
  useCount?: number;
  /** "Last Used At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastUsedAt?: string;
};

/** What you may write when creating or updating a record in the "Email Templates" table. */
export type EmailTemplatesRecordInput = {
  name: string | null;
  subject: string | null;
  body: string | null;
  category: string | null;
  ownerId: string | null;
  shared: string | boolean | null;
  archived: string | boolean | null;
  useCount: string | number | null;
  lastUsedAt: string | Date | null;
};

/** A record in the "Sequences" table, as it is read back. */
export type SequencesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  description?: string;
  ownerId?: string;
  status?: "Active" | "Paused" | "Archived" | string;
  steps?: string;
  settings?: string;
  shared?: boolean;
};

/** What you may write when creating or updating a record in the "Sequences" table. */
export type SequencesRecordInput = {
  name: string | null;
  description: string | null;
  ownerId: string | null;
  status: "Active" | "Paused" | "Archived" | string | null;
  steps: string | null;
  settings: string | null;
  shared: string | boolean | null;
};

/** A record in the "Enrollments" table, as it is read back. */
export type EnrollmentsRecordType = {
  id: string;
  /** Primary field. "Sequence Id" */
  sequenceId?: string;
  contactId?: string;
  dealId?: string;
  ownerId?: string;
  status?: "Active" | "Paused" | "Finished" | "Exited" | string;
  /** "Step Index". 0 decimal places, format: local (e.g. 1,000,000.50) */
  stepIndex?: number;
  /** "Next Run At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  nextRunAt?: string;
  /** "Enrolled At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  enrolledAt?: string;
  /** "Last Step At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastStepAt?: string;
  /** "Finished At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  finishedAt?: string;
  exitReason?: string;
  enrolledById?: string;
};

/** What you may write when creating or updating a record in the "Enrollments" table. */
export type EnrollmentsRecordInput = {
  sequenceId: string | null;
  contactId: string | null;
  dealId: string | null;
  ownerId: string | null;
  status: "Active" | "Paused" | "Finished" | "Exited" | string | null;
  stepIndex: string | number | null;
  nextRunAt: string | Date | null;
  enrolledAt: string | Date | null;
  lastStepAt: string | Date | null;
  finishedAt: string | Date | null;
  exitReason: string | null;
  enrolledById: string | null;
};

/** A record in the "Forms" table, as it is read back. */
export type FormsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  slug?: string;
  intro?: string;
  fields?: string;
  status?: "Live" | "Paused" | string;
  submitLabel?: string;
  successMessage?: string;
  redirectUrl?: string;
  assignment?: "Round Robin" | "Member" | "Unassigned" | string;
  assigneeId?: string;
  source?: string;
  notifyIds?: string;
  sequenceId?: string;
  tagIds?: string;
  ownerId?: string;
  /** "Submission Count". 0 decimal places, format: local (e.g. 1,000,000.50) */
  submissionCount?: number;
  /** "Last Submission At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastSubmissionAt?: string;
  archived?: boolean;
};

/** What you may write when creating or updating a record in the "Forms" table. */
export type FormsRecordInput = {
  name: string | null;
  slug: string | null;
  intro: string | null;
  fields: string | null;
  status: "Live" | "Paused" | string | null;
  submitLabel: string | null;
  successMessage: string | null;
  redirectUrl: string | null;
  assignment: "Round Robin" | "Member" | "Unassigned" | string | null;
  assigneeId: string | null;
  source: string | null;
  notifyIds: string | null;
  sequenceId: string | null;
  tagIds: string | null;
  ownerId: string | null;
  submissionCount: string | number | null;
  lastSubmissionAt: string | Date | null;
  archived: string | boolean | null;
};

/** A record in the "Submissions" table, as it is read back. */
export type SubmissionsRecordType = {
  id: string;
  /** Primary field. "Form Id" */
  formId?: string;
  email?: string;
  name?: string;
  answers?: string;
  leadId?: string;
  contactId?: string;
  outcome?: "New Lead" | "Existing Lead" | "Existing Contact" | "Spam" | string;
  /** "Submitted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  submittedAt?: string;
  pageUrl?: string;
  referrer?: string;
  utm?: string;
};

/** What you may write when creating or updating a record in the "Submissions" table. */
export type SubmissionsRecordInput = {
  formId: string | null;
  email: string | null;
  name: string | null;
  answers: string | null;
  leadId: string | null;
  contactId: string | null;
  outcome: "New Lead" | "Existing Lead" | "Existing Contact" | "Spam" | string | null;
  submittedAt: string | Date | null;
  pageUrl: string | null;
  referrer: string | null;
  utm: string | null;
};

/** A record in the "Booking Pages" table, as it is read back. */
export type BookingPagesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  slug?: string;
  description?: string;
  hostIds?: string;
  /** "Duration Minutes". 0 decimal places, format: local (e.g. 1,000,000.50) */
  durationMinutes?: number;
  /** "Buffer Minutes". 0 decimal places, format: local (e.g. 1,000,000.50) */
  bufferMinutes?: number;
  /** "Min Notice Hours". 0 decimal places, format: local (e.g. 1,000,000.50) */
  minNoticeHours?: number;
  /** "Window Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  windowDays?: number;
  availability?: string;
  timezone?: string;
  location?: string;
  questions?: string;
  active?: boolean;
  ownerId?: string;
  /** "Booking Count". 0 decimal places, format: local (e.g. 1,000,000.50) */
  bookingCount?: number;
  /** "Rotation Cursor". 0 decimal places, format: local (e.g. 1,000,000.50) */
  rotationCursor?: number;
};

/** What you may write when creating or updating a record in the "Booking Pages" table. */
export type BookingPagesRecordInput = {
  name: string | null;
  slug: string | null;
  description: string | null;
  hostIds: string | null;
  durationMinutes: string | number | null;
  bufferMinutes: string | number | null;
  minNoticeHours: string | number | null;
  windowDays: string | number | null;
  availability: string | null;
  timezone: string | null;
  location: string | null;
  questions: string | null;
  active: string | boolean | null;
  ownerId: string | null;
  bookingCount: string | number | null;
  rotationCursor: string | number | null;
};

/** A record in the "Views" table, as it is read back. */
export type ViewsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  scope?: "Deals" | "Companies" | "Contacts" | "Leads" | "Tasks" | "Activities" | "Quotes" | string;
  config?: string;
  ownerId?: string;
  shared?: boolean;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Views" table. */
export type ViewsRecordInput = {
  name: string | null;
  scope: "Deals" | "Companies" | "Contacts" | "Leads" | "Tasks" | "Activities" | "Quotes" | string | null;
  config: string | null;
  ownerId: string | null;
  shared: string | boolean | null;
  position: string | number | null;
};

/** A record in the "Custom Fields" table, as it is read back. */
export type CustomFieldsRecordType = {
  id: string;
  /** Primary field. "Label" */
  label?: string;
  key?: string;
  object?: "Company" | "Contact" | "Deal" | "Lead" | string;
  type?: "Text" | "Long Text" | "Number" | "Currency" | "Date" | "Select" | "Multi Select" | "Checkbox" | "URL" | string;
  options?: string;
  helpText?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  required?: boolean;
  archived?: boolean;
};

/** What you may write when creating or updating a record in the "Custom Fields" table. */
export type CustomFieldsRecordInput = {
  label: string | null;
  key: string | null;
  object: "Company" | "Contact" | "Deal" | "Lead" | string | null;
  type: "Text" | "Long Text" | "Number" | "Currency" | "Date" | "Select" | "Multi Select" | "Checkbox" | "URL" | string | null;
  options: string | null;
  helpText: string | null;
  position: string | number | null;
  required: string | boolean | null;
  archived: string | boolean | null;
};

/** A record in the "Choices" table, as it is read back. */
export type ChoicesRecordType = {
  id: string;
  /** Primary field. "Label" */
  label?: string;
  list?: "Industry" | "Lead Source" | "Lost Reason" | "Disqualify Reason" | string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  archived?: boolean;
};

/** What you may write when creating or updating a record in the "Choices" table. */
export type ChoicesRecordInput = {
  label: string | null;
  list: "Industry" | "Lead Source" | "Lost Reason" | "Disqualify Reason" | string | null;
  position: string | number | null;
  archived: string | boolean | null;
};

/** A record in the "Tags" table, as it is read back. */
export type TagsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  color?: string;
  description?: string;
};

/** What you may write when creating or updating a record in the "Tags" table. */
export type TagsRecordInput = {
  name: string | null;
  color: string | null;
  description: string | null;
};

/** A record in the "Notifications" table, as it is read back. */
export type NotificationsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  recipientId?: string;
  kind?: string;
  body?: string;
  link?: string;
  entityType?: string;
  entityId?: string;
  actorId?: string;
  /** "Read At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  readAt?: string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
};

/** What you may write when creating or updating a record in the "Notifications" table. */
export type NotificationsRecordInput = {
  title: string | null;
  recipientId: string | null;
  kind: string | null;
  body: string | null;
  link: string | null;
  entityType: string | null;
  entityId: string | null;
  actorId: string | null;
  readAt: string | Date | null;
  occurredAt: string | Date | null;
};

/** A record in the "Events" table, as it is read back. */
export type EventsRecordType = {
  id: string;
  /** Primary field. "Summary" */
  summary?: string;
  kind?: string;
  entityType?: string;
  entityId?: string;
  actorId?: string;
  data?: string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
  companyId?: string;
  contactId?: string;
  dealId?: string;
  leadId?: string;
};

/** What you may write when creating or updating a record in the "Events" table. */
export type EventsRecordInput = {
  summary: string | null;
  kind: string | null;
  entityType: string | null;
  entityId: string | null;
  actorId: string | null;
  data: string | null;
  occurredAt: string | Date | null;
  companyId: string | null;
  contactId: string | null;
  dealId: string | null;
  leadId: string | null;
};

/** A record in the "Documents" table, as it is read back. */
export type DocumentsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  url?: string;
  /** "Size". 0 decimal places, format: local (e.g. 1,000,000.50) */
  size?: number;
  contentType?: string;
  companyId?: string;
  contactId?: string;
  dealId?: string;
  leadId?: string;
  uploadedById?: string;
};

/** What you may write when creating or updating a record in the "Documents" table. */
export type DocumentsRecordInput = {
  name: string | null;
  url: string | null;
  size: string | number | null;
  contentType: string | null;
  companyId: string | null;
  contactId: string | null;
  dealId: string | null;
  leadId: string | null;
  uploadedById: string | null;
};

/** A record in the "Quotas" table, as it is read back. */
export type QuotasRecordType = {
  id: string;
  /** Primary field. "Member Id" */
  memberId?: string;
  period?: "Month" | "Quarter" | "Year" | string;
  /** "Period Start". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  periodStart?: string;
  metric?: "Revenue" | "Deals Won" | "Meetings" | "Calls" | string;
  /** "Target". 2 decimal places, format: local (e.g. 1,000,000.50) */
  target?: number;
};

/** What you may write when creating or updating a record in the "Quotas" table. */
export type QuotasRecordInput = {
  memberId: string | null;
  period: "Month" | "Quarter" | "Year" | string | null;
  periodStart: string | Date | null;
  metric: "Revenue" | "Deals Won" | "Meetings" | "Calls" | string | null;
  target: string | number | null;
};

/** A record in the "Settings" table, as it is read back. */
export type SettingsRecordType = {
  id: string;
  /** Primary field. "Organization Name" */
  organizationName?: string;
  currency?: string;
  timezone?: string;
  /** "Fiscal Year Start Month". 0 decimal places, format: local (e.g. 1,000,000.50) */
  fiscalYearStartMonth?: number;
  logoUrl?: string;
  brandColor?: string;
  defaultRole?: string;
  leadRouting?: string;
  quoteDefaults?: string;
  /** "Next Quote Number". 0 decimal places, format: local (e.g. 1,000,000.50) */
  nextQuoteNumber?: number;
  emailFooter?: string;
  mailingAddress?: string;
  pagesUrl?: string;
  preferences?: string;
  /** "Seeded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  seededAt?: string;
  /** "Demo Removed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  demoRemovedAt?: string;
};

/** What you may write when creating or updating a record in the "Settings" table. */
export type SettingsRecordInput = {
  organizationName: string | null;
  currency: string | null;
  timezone: string | null;
  fiscalYearStartMonth: string | number | null;
  logoUrl: string | null;
  brandColor: string | null;
  defaultRole: string | null;
  leadRouting: string | null;
  quoteDefaults: string | null;
  nextQuoteNumber: string | number | null;
  emailFooter: string | null;
  mailingAddress: string | null;
  pagesUrl: string | null;
  preferences: string | null;
  seededAt: string | Date | null;
  demoRemovedAt: string | Date | null;
};

/** A record in the "Automations" table, as it is read back. */
export type AutomationsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  description?: string;
  trigger?: string;
  conditions?: string;
  actions?: string;
  active?: boolean;
  ownerId?: string;
  /** "Run Count". 0 decimal places, format: local (e.g. 1,000,000.50) */
  runCount?: number;
  /** "Last Run At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastRunAt?: string;
};

/** What you may write when creating or updating a record in the "Automations" table. */
export type AutomationsRecordInput = {
  name: string | null;
  description: string | null;
  trigger: string | null;
  conditions: string | null;
  actions: string | null;
  active: string | boolean | null;
  ownerId: string | null;
  runCount: string | number | null;
  lastRunAt: string | Date | null;
};

/** A record in the "Automation Runs" table, as it is read back. */
export type AutomationRunsRecordType = {
  id: string;
  /** Primary field. "Automation Id" */
  automationId?: string;
  entityType?: string;
  entityId?: string;
  status?: "Succeeded" | "Failed" | "Skipped" | string;
  detail?: string;
  /** "Ran At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  ranAt?: string;
};

/** What you may write when creating or updating a record in the "Automation Runs" table. */
export type AutomationRunsRecordInput = {
  automationId: string | null;
  entityType: string | null;
  entityId: string | null;
  status: "Succeeded" | "Failed" | "Skipped" | string | null;
  detail: string | null;
  ranAt: string | Date | null;
};

/** A record in the "Imports" table, as it is read back. */
export type ImportsRecordType = {
  id: string;
  /** Primary field. "File Name" */
  fileName?: string;
  object?: "Companies" | "Contacts" | "Deals" | "Leads" | string;
  status?: "Running" | "Completed" | "Failed" | "Undone" | string;
  /** "Row Count". 0 decimal places, format: local (e.g. 1,000,000.50) */
  rowCount?: number;
  /** "Created Count". 0 decimal places, format: local (e.g. 1,000,000.50) */
  createdCount?: number;
  /** "Updated Count". 0 decimal places, format: local (e.g. 1,000,000.50) */
  updatedCount?: number;
  /** "Skipped Count". 0 decimal places, format: local (e.g. 1,000,000.50) */
  skippedCount?: number;
  errors?: string;
  mapping?: string;
  actorId?: string;
  /** "Undone At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  undoneAt?: string;
};

/** What you may write when creating or updating a record in the "Imports" table. */
export type ImportsRecordInput = {
  fileName: string | null;
  object: "Companies" | "Contacts" | "Deals" | "Leads" | string | null;
  status: "Running" | "Completed" | "Failed" | "Undone" | string | null;
  rowCount: string | number | null;
  createdCount: string | number | null;
  updatedCount: string | number | null;
  skippedCount: string | number | null;
  errors: string | null;
  mapping: string | null;
  actorId: string | null;
  undoneAt: string | Date | null;
};

export interface NotificationLink {
  path?: string;
  params?: Record<string, string>;
}

export interface NotificationsCreateParams {
  recipients: string[];
  title: string;
  body?: string;
  link?: NotificationLink;
  path?: string;
  params?: Record<string, string>;
  payload?: Record<string, unknown>;
  idempotencyKey?: string;
}

export type NotificationsCreateResult =
  | { created: number }
  | { created: 0; preview: true; wouldCreate: number };

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  members: createTableClient<MembersRecordType, MembersRecordInput>('Members'), // "Members"
  teams: createTableClient<TeamsRecordType, TeamsRecordInput>('Teams'), // "Teams"
  companies: createTableClient<CompaniesRecordType, CompaniesRecordInput>('Companies'), // "Companies"
  contacts: createTableClient<ContactsRecordType, ContactsRecordInput>('Contacts'), // "Contacts"
  leads: createTableClient<LeadsRecordType, LeadsRecordInput>('Leads'), // "Leads"
  pipelines: createTableClient<PipelinesRecordType, PipelinesRecordInput>('Pipelines'), // "Pipelines"
  stages: createTableClient<StagesRecordType, StagesRecordInput>('Stages'), // "Stages"
  deals: createTableClient<DealsRecordType, DealsRecordInput>('Deals'), // "Deals"
  dealContacts: createTableClient<DealContactsRecordType, DealContactsRecordInput>('DealContacts'), // "Deal Contacts"
  stageChanges: createTableClient<StageChangesRecordType, StageChangesRecordInput>('StageChanges'), // "Stage Changes"
  activities: createTableClient<ActivitiesRecordType, ActivitiesRecordInput>('Activities'), // "Activities"
  tasks: createTableClient<TasksRecordType, TasksRecordInput>('Tasks'), // "Tasks"
  products: createTableClient<ProductsRecordType, ProductsRecordInput>('Products'), // "Products"
  lineItems: createTableClient<LineItemsRecordType, LineItemsRecordInput>('LineItems'), // "Line Items"
  quotes: createTableClient<QuotesRecordType, QuotesRecordInput>('Quotes'), // "Quotes"
  emailTemplates: createTableClient<EmailTemplatesRecordType, EmailTemplatesRecordInput>('EmailTemplates'), // "Email Templates"
  sequences: createTableClient<SequencesRecordType, SequencesRecordInput>('Sequences'), // "Sequences"
  enrollments: createTableClient<EnrollmentsRecordType, EnrollmentsRecordInput>('Enrollments'), // "Enrollments"
  forms: createTableClient<FormsRecordType, FormsRecordInput>('Forms'), // "Forms"
  submissions: createTableClient<SubmissionsRecordType, SubmissionsRecordInput>('Submissions'), // "Submissions"
  bookingPages: createTableClient<BookingPagesRecordType, BookingPagesRecordInput>('BookingPages'), // "Booking Pages"
  views: createTableClient<ViewsRecordType, ViewsRecordInput>('Views'), // "Views"
  customFields: createTableClient<CustomFieldsRecordType, CustomFieldsRecordInput>('CustomFields'), // "Custom Fields"
  choices: createTableClient<ChoicesRecordType, ChoicesRecordInput>('Choices'), // "Choices"
  tags: createTableClient<TagsRecordType, TagsRecordInput>('Tags'), // "Tags"
  notifications: createTableClient<NotificationsRecordType, NotificationsRecordInput>('Notifications'), // "Notifications"
  events: createTableClient<EventsRecordType, EventsRecordInput>('Events'), // "Events"
  documents: createTableClient<DocumentsRecordType, DocumentsRecordInput>('Documents'), // "Documents"
  quotas: createTableClient<QuotasRecordType, QuotasRecordInput>('Quotas'), // "Quotas"
  settings: createTableClient<SettingsRecordType, SettingsRecordInput>('Settings'), // "Settings"
  automations: createTableClient<AutomationsRecordType, AutomationsRecordInput>('Automations'), // "Automations"
  automationRuns: createTableClient<AutomationRunsRecordType, AutomationRunsRecordInput>('AutomationRuns'), // "Automation Runs"
  imports: createTableClient<ImportsRecordType, ImportsRecordInput>('Imports'), // "Imports"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
