import { lazy, Suspense } from 'react';
import { HashRouter, Route, Routes } from 'react-router-dom';
import { Toaster } from 'sonner';
import { Loading, Notice } from './ui/kit';

// The public pages follow the visitor's operating system — there is no theme
// switch on a page someone opens once from an email. main.tsx is generated by
// the platform, so this lives in the app's own entry point.
const darkQuery = typeof window !== 'undefined' ? window.matchMedia('(prefers-color-scheme: dark)') : null;
const applySystemTheme = () => document.documentElement.classList.toggle('dark', Boolean(darkQuery?.matches));
applySystemTheme();
darkQuery?.addEventListener('change', applySystemTheme);

/**
 * The public side of the CRM. Four things a buyer can land on, each from a
 * link someone in the CRM sent them:
 *
 *   /f/:slug          a web form
 *   /m/:slug          a meeting link  ·  /m/booking/:token  manage a booking
 *   /q/:token         a quote to read, accept or decline
 *   /u/:token         unsubscribe
 *
 * Pages are lazy so one page can never stop another from loading.
 */
const FormPage = lazy(() => import('./pages/FormPage'));
const MeetingPage = lazy(() => import('./pages/MeetingPage'));
const BookingPage = lazy(() => import('./pages/BookingPage'));
const QuotePage = lazy(() => import('./pages/QuotePage'));
const UnsubscribePage = lazy(() => import('./pages/UnsubscribePage'));

export default function App() {
  return (
    <HashRouter>
      <Suspense fallback={<Loading />}>
        <Routes>
          <Route path="/f/:slug" element={<FormPage />} />
          <Route path="/m/booking/:token" element={<BookingPage />} />
          <Route path="/m/:slug" element={<MeetingPage />} />
          <Route path="/q/:token" element={<QuotePage />} />
          <Route path="/u/:token" element={<UnsubscribePage />} />
          <Route path="*" element={<Notice title="Nothing to see here">This page is opened from a link — check the one you were sent.</Notice>} />
        </Routes>
      </Suspense>
      <Toaster position="top-center" offset={16} />
    </HashRouter>
  );
}
